### ISSUE TITLE
OClassLoaderHelper uses javax.imageio.spi.ServiceRegistry

### ISSUE THREAD

**Issue by jdillon** [orientechnologies/orientdb#3402]
Seems odd that its depending on javax.imageio libraries here.

Suggest you guys change to use java.util.ServiceLocator instead, which IIUC is essentially the same thing you need here.

**Comment by tglman** [comment]
yes, i also wondered a few times why was imageio there, i'll change this with (java.util.ServiceLoader)[https://docs.oracle.com/javase/6/docs/api/java/util/ServiceLoader.html] after we released 2.0 final.

the reason for not do it now is that we don't want to mess up 2 days before release, and this may impact some osgi environment.

**Comment by jdillon** [comment]
FYI, using imageio impl may actually prevent proper usage in osgi:

http://stackoverflow.com/questions/12664287/does-javax-imageio-spi-serviceregistry-work-in-an-osgi-container

**Comment by lvca** [comment]
@tglman WDYT?

**Comment by jdillon** [comment]
FTR I can't say if changing to the java.util.ServiceLoader will actually resolve this yet.  I may run some local tests, as it may still be problematic due to how the classloader is selected by consumers of OClassLoaderHelper.  Will let you guys know what we find.

**Comment by cwilper** [comment]
Update: I just tested switching to java.util.ServiceLoader and by itself, it doesn't change the behavior for the issue we're seeing (karaf still can't find OGraphFunctionFactory, so graph functions show up as missing when you try to use them in select statements).

**Comment by jdillon** [comment]
thanks @cwilper, we'll have to dig a bit more to see if there is an issue with how we have the CL setup or if its a more fundamental issue of how orient is loading these based on the loading with specific CL `orientClassLoader  = OSQLEngine.class.getClassLoader();`

**Comment by lvca** [comment]
Thanks guys, we really appreciate your work on this.

**Comment by mcculls** [comment]
FYI, a quick solution to this is to make the graphdb bundle a fragment of the core bundle:
```
diff --git a/graphdb/pom.xml b/graphdb/pom.xml
index 8f4d342..52b76c6 100644
--- a/graphdb/pom.xml
+++ b/graphdb/pom.xml
@@ -40,6 +40,9 @@
         <javac.src.version>1.6</javac.src.version>
         <javac.target.version>1.6</javac.target.version>
         <jar.manifest.mainclass>com.orientechnologies.orient.server.OServerMain</jar.manifest.mainclass>
+        <osgi.fragment.host>
+            com.orientechnologies.orientdb-core
+        </osgi.fragment.host>
         <osgi.import>
             com.tinkerpop.blueprints;resolution:=optional,
             com.tinkerpop.gremlin.groovy.jsr223;resolution:=optional,
```
This will merge their contents at runtime in OSGi so that they effectively share the same classpath and should therefore make the graph functions visible.

**Comment by lvca** [comment]
I'm not an OSGi expert. Everybody agrees on this change?

**Comment by tglman** [comment]
fixed closing
