### ISSUE TITLE
Clustering

### ISSUE THREAD

**Issue by vitorenesduarte** [orientechnologies/orientdb#3578]
Hi,
__v2.0.2__
- create some database and:
```sql
create class User
alter cluster User name User0
alter class user addcluster User1
```
- change __hazelcast.xml__ to:
```xml
<hazelcast
        xsi:schemaLocation="http://www.hazelcast.com/schema/config hazelcast-config-3.0.xsd"
        xmlns="http://www.hazelcast.com/schema/config" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
        <group>
                <name>orientdb</name>
                <password>orientdb</password>
        </group>
        <network>
                <port auto-increment="true">2434</port>
                <join>
                        <multicast enabled="false">
                                <multicast-group>235.1.1.1</multicast-group>
                                <multicast-port>2434</multicast-port>
                        </multicast>
                        <tcp-ip enabled="true">
                                <member>10.0.71.5:2434</member>
                                <member>10.0.71.5:2435</member>
                        </tcp-ip>
                </join>
        </network>
        <executor-service>
                <pool-size>16</pool-size>
        </executor-service>
</hazelcast>
```
- change __default-distributed-db-config.json__ to:
```json
{
    "autoDeploy": true,
    "hotAlignment": false,
    "executionMode": "undefined",
    "readQuorum": 1,
    "writeQuorum": 2,
    "failureAvailableNodesLessQuorum": false,
    "readYourWrites": true,
    "clusters": {
        "internal": {
        },
        "index": {
        },
        "User0":{
                "servers" : [ "node0" ]
        },
        "User1":{
                "servers" : [ "node1" ]
        },
        "*": {
            "servers" : [ "<NEW_NODE>" ]
        }
    }
}
```
- create a copy of __orientdb-community-2.0.2__ folder
- run both __dserver.sh__; call the first __node0__, the second __node1__
- [here](https://www.dropbox.com/s/l3iuvm1bcepglil/sharding.tar.gz?dl=0) are the dbs I have after the steps above.
- now from studio:
```sql
# from localhost:2480, which is the port of node0
insert into cluster:User0 set name = 'User0_80'
select from User # returns the expected
```
```sql
# from localhost:2481
select from User # shows nothing
# I was hoping to see info from all clusters
```
-----
```sql
# from localhost:2480
insert into cluster:User1 set name = 'User1_80' # returns the recorded inserted
# from what I read, I thought only master node could insert in his cluster
select from User # returns 'User0_80' and 'User1_80'
```
```sql
# from localhost:2481
select from User # returns only 'User1_80'
```
----
```sql
# from localhost:2481
insert into cluster:User1 set name = 'User1_81'
```
```sql
# from localhost:2480
select from User # returns 'User0_80' and 'User1_80' and 'User1_81'
```
----
And when trying this:
```sql
# from localhost:2481
insert into cluster:User0 set name = 'User0_81'
```
I got:
```bash
com.orientechnologies.orient.core.exception.OStorageException: Cannot route COMMAND operation to the distributed node
--> com.orientechnologies.orient.server.distributed.ODistributedException: Quorum 2 not reached for request ....
```

What is going on? Nothing is coherent. Maybe there's something wrong with my configuration.
Sorry for the long post.

**Comment by lvca** [comment]
Please could you retry with 2.0.3-SNAPSHOT?

**Comment by vitorenesduarte** [comment]
Yes, can you provide the link?

**Comment by vitorenesduarte** [comment]
You mean the latest [here](https://oss.sonatype.org/content/repositories/snapshots/com/orientechnologies/orientdb-community/2.0.3-SNAPSHOT/) right?
I'll try.

**Comment by vitorenesduarte** [comment]
- repeat first 5 steps
- kill both __dserver.sh__
- [here](https://www.dropbox.com/s/ki0qx7hjqzth75z/sharding2.tar.gz?dl=0) are the dbs after
- restart both dserver.sh: 
  * node0 -> 2424/2480/2434
  * node1 -> 2425/2481/2435
- repeat same steps from studio: the behaviour is not the same but I still can't make sense of it.

**Comment by vitorenesduarte** [comment]
@lvca is this an issue or the sharding is not properly configured?

**Comment by lvca** [comment]
I'd need the logs of both servers. You could avoid changing `change default-distributed-db-config.json` and let OrientDB to that automatically: at startup of second node, OrientDB will create User_node1 cluster.

**Comment by vitorenesduarte** [comment]
Hi @lvca.
If I do as you say, if I understood correctly, I will have replicas, not shards (maybe the title of this issue should be __sharding__ instead of clustering).

And with replicas I didn't have problems so far.

But image this situation: I have one machine on Amazon, but it has reached its limit. I buy another machine and start it as a distributed server too (let's call the machines nodes). The second one will copy all the info from the first node, and now I have two nodes that have reached their limit, and both will keep growing. The solution for this is sharding right? I just can't make it work.

I'll try again and send you the logs.

**Comment by lvca** [comment]
Sorry I didn't see you didn't activate replica at all. I can confirm what you expected is how OrientDB should work, so having a test case would be amazing to fix it asap.

**Comment by vitorenesduarte** [comment]
- Same situation
- [here](https://www.dropbox.com/s/ytx55flvmhriq4e/Sharding.tar.gz?dl=0) are the dbs before the test
- the test (sorry for it, never used JUnit):
```java
public class Sharding {

   private static final String URL_NODE_ZERO = "remote:localhost:2424/Sharding";
   private static final String URL_NODE_ONE = "remote:localhost:2425/Sharding";
   private static final String DB_USER = "admin";
   private static final String DB_PASS = "admin";

   private static final ODatabaseDocument dbNodeZero = new ODatabaseDocumentTx(URL_NODE_ZERO);
   private static final ODatabaseDocument dbNodeOne = new ODatabaseDocumentTx(URL_NODE_ONE);

   public static void main(String[] args) {
      try {
         dbNodeZero.open(DB_USER, DB_PASS);
         dbNodeOne.open(DB_USER, DB_PASS);
         
         
         execute(dbNodeZero, "insert into cluster:User0 set name = 'user0'");
         
         if(!"user0".equals(getResult(execute(dbNodeZero, "select from cluster:User0")))){
            System.out.println("test0 : fail");
         }
         if(!"".equals(getResult(execute(dbNodeZero, "select from cluster:User1")))){
            System.out.println("test1 : fail");
         }
         if(!"user0".equals(getResult(execute(dbNodeZero, "select from User")))){
            System.out.println("test2 : fail");
         }
         if(!"user0".equals(getResult(execute(dbNodeOne, "select from cluster:User0")))){
            System.out.println("test3 : fail");
         }
         if(!"".equals(getResult(execute(dbNodeOne, "select from cluster:User1")))){
            System.out.println("test4 : fail");
         }
         if(!"user0".equals(getResult(execute(dbNodeOne, "select from User")))){
            System.out.println("test5 : fail");
         }

         execute(dbNodeOne, "insert into cluster:User1 set name = 'user1'");
         
         if(!"user0".equals(getResult(execute(dbNodeZero, "select from cluster:User0")))){
            System.out.println("test6 : fail");
         }
         if(!"user1".equals(getResult(execute(dbNodeZero, "select from cluster:User1")))){
            System.out.println("test7 : fail");
         }
         if(!"user0user1".equals(getResult(execute(dbNodeZero, "select from User")))){
            System.out.println("test8 : fail");
         }
         if(!"user0".equals(getResult(execute(dbNodeOne, "select from cluster:User0")))){
            System.out.println("test9 : fail");
         }
         if(!"user1".equals(getResult(execute(dbNodeOne, "select from cluster:User1")))){
            System.out.println("test10 : fail");
         }
         if(!"user0user1".equals(getResult(execute(dbNodeOne, "select from User")))){
            System.out.println("test11 : fail");
         }
         
      } finally {
         dbNodeZero.close();
         dbNodeOne.close();
      }
   }

   static Object execute(ODatabaseDocument db, String command) {
      return db.command(new OCommandSQL(command)).execute();
   }

   static String getResult(Object o) {
      StringBuilder result = new StringBuilder();
      if (o instanceof List) {
         List<ODocument> resultList = (List) o;
         for (ODocument d : resultList) {
            result.append(d.field("name"));
         }
      }
      return result.toString();
   }
}
```
- output:
```bash
test3 : fail
test5 : fail
test9 : fail
test11 : fail
```

**Comment by srgg** [comment]
@lvca this issue looks like pretty similar to #3479

**Comment by lvca** [comment]
Is this still open? We fixed #3479. Please could you retry it?

**Comment by vitorenesduarte** [comment]
@lvca That issue was closed before I open this one. But I can try if you say it's fixed.

**Comment by vitorenesduarte** [comment]
Just tried with __2.0.5__.
- the output:
```bash
test3 : fail
test5 : fail
test7 : fail
test8 : fail
test9 : fail
test11 : fail
```

**Comment by lvca** [comment]
Tried on 2.0.5 all tests pass. Please delete all the previous records before to launch it.

**Comment by vitorenesduarte** [comment]
@lvca I just download __2.0.5.__ again from [here](http://www.orientechnologies.com/download/), followed all steps stated above, and it still fails:
```bash
test3 : fail
test5 : fail
test7 : fail
test8 : fail
test9 : fail
test11 : fail
```

**Comment by lvca** [comment]
I tried `2.0.x` branch that is 2.0.5 + some fix. Dunno if there is something in 2.0.x branch. However your test pass 100%.

**Comment by vitorenesduarte** [comment]
@lvca I just download, and the output is:
`bash

**Comment by vitorenesduarte** [comment]
@lvca I just downloaded __2.0.6-20150317.182256-8__ from [here](https://oss.sonatype.org/content/repositories/snapshots/com/orientechnologies/orientdb-community/2.0.6-SNAPSHOT/), and the output still is:
```bash
test3 : fail
test5 : fail
test7 : fail
test8 : fail
test9 : fail
test11 : fail
```

**Comment by vitorenesduarte** [comment]
@lvca can you try again? I can't make sharding work.

**Comment by vitorenesduarte** [comment]
@lvca can you explain how all tests pass? Your config files are the same as mine?

**Comment by lvca** [comment]
Tested again: works like a sharm. Pay attention you don't have asynchronous replication mode or writeQuorum < 2. Check not only $ORIENTDB_HOME/config/default-distributed-db-config.json but also the same file inside your database directory: if present that file wins. In case you're good, please attach on a GIST the log of server1.

**Comment by vitorenesduarte** [comment]
Hi @lvca. Sorry I took so long to answer. I just downloaded __v2.0.6__ to ran the test again.

There's a file `$ORIENTDB_HOME/databases/DatabaseName/distributed-config.json` but it's created after I run `./dserver.sh`. In the logs of both nodes I can see this happening. __node0__ e.g.:
```bash
2015-04-06 16:58:39:640 INFO  [node0] loaded database configuration from disk: /Users/vitorenes/Desktop/orientdb-community-2.0.6_node0/databases/Sharding/distributed-config.json [OHazelcastPlugin]
```
The content of those files in [node0](https://gist.github.com/vitorenesduarte/34147e99f6219bd239a1) and [node1](https://gist.github.com/vitorenesduarte/9e191cd5ead2f95646e3).
_____
If I run the test, the output still is:
```bash
test3 : fail
test5 : fail
test7 : fail
test8 : fail
test9 : fail
test11 : fail
```

The logs of [node0](https://gist.github.com/vitorenesduarte/a39eb45e232ba2e9aa73) and [node1](https://gist.github.com/vitorenesduarte/8d014da7de34a1304e1f).

**Comment by lvca** [comment]
Hey Vitor,
2 servers don't see each others. Look at this output:

Members [1] {
  Member [10.0.71.39]:2435 this
}

It should say [2] with 2 members.

**Comment by vitorenesduarte** [comment]
Hi @lvca. Sorry, you're right. 
Just ran again, and they they can see each other.
The logs of [node0](https://gist.github.com/vitorenesduarte/00bb79e7a7bf3fd9b898) and [node1](https://gist.github.com/vitorenesduarte/1a9241842be22bf6af1b).

- the output:
```bash
test3 : fail
test5 : fail
test9 : fail
test11 : fail
```

Your hazelcast configuration is the same as mine?

**Comment by lvca** [comment]
Did you delete all the previous entries before the test?

**Comment by vitorenesduarte** [comment]
Yes, I always run the tests with dservers running for the first time.

**Comment by vitorenesduarte** [comment]
@lvca to create to the clusters, did you (as I wrote above):
```sql
create class User
alter cluster User name User0
alter class User addcluster User1
```
or:
```sql
create class User
alter class User addcluster User0
alter class User addcluster User1
```
Because, with the last one, all the tests pass.
