### ISSUE TITLE
Select statement against large database produce OOM in Orient Distributed server 2.0.12

### ISSUE THREAD

**Issue by shlapkov** [orientechnologies/orientdb#4631]
Steps to reproduce:
1.	Download Orient DB community editions 2.0.12 from : http://orientdb.com/download/
2.	Copy any large database 1.7.x into: orientdb-community-2.0.12/databases
3.	Start: dserver.bat from bin folder. Start console.bat connect to remote db. “connect remote:localhost:2424/spectrum admin admin”
4.	Run: “select * from platform-Version limit=50000”
5.	Notice OOM error on server:

Fetching error on record #49:3753
com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #35:3753
(cluster: platform-versioncontents)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODat
baseDocumentTx.java:1640)
        at com.orientechnologies.orient.core.tx.OTransactionNoTx.loadRecord(OTransactionNoTx.java:8
)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocument
x.java:1452)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocument
x.java:118)
        at com.orientechnologies.orient.core.record.impl.ODocument.field(ODocument.java:871)
        at com.orientechnologies.orient.core.fetch.OFetchHelper.processRecordRidMap(OFetchHelper.ja
a:140)
        at com.orientechnologies.orient.core.fetch.OFetchHelper.fetch(OFetchHelper.java:70)
        at com.orientechnologies.orient.server.network.protocol.binary.OAbstractCommandResultListen
r.fetchRecord(OAbstractCommandResultListener.java:54)
        at com.orientechnologies.orient.server.network.protocol.binary.OSyncCommandResultListener.r
sult(OSyncCommandResultListener.java:40)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.comma
d(ONetworkProtocolBinary.java:1229)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execu
eRequest(ONetworkProtocolBinary.java:390)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstra
t.execute(OBinaryNetworkProtocolAbstract.java:217)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
Caused by: java.lang.OutOfMemoryError: Java heap space
Fetching error on record #49:3754
com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #35:3754
(cluster: platform-versioncontents)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODat
baseDocumentTx.java:1640)
        at com.orientechnologies.orient.core.tx.OTransactionNoTx.loadRecord(OTransactionNoTx.java:8
)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocument
x.java:1452)
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocument
x.java:118)
        at com.orientechnologies.orient.core.record.impl.ODocument.field(ODocument.java:871)
        at com.orientechnologies.orient.core.fetch.OFetchHelper.processRecordRidMap(OFetchHelper.ja
a:140)
        at com.orientechnologies.orient.core.fetch.OFetchHelper.fetch(OFetchHelper.java:70)
        at com.orientechnologies.orient.server.network.protocol.binary.OAbstractCommandResultListen
r.fetchRecord(OAbstractCommandResultListener.java:54)
        at com.orientechnologies.orient.server.network.protocol.binary.OSyncCommandResultListener.r
sult(OSyncCommandResultListener.java:40)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.comma
d(ONetworkProtocolBinary.java:1229)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execu
eRequest(ONetworkProtocolBinary.java:390)
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstra
t.execute(OBinaryNetworkProtocolAbstract.java:217)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:69)
Caused by: java.lang.OutOfMemoryError: Java heap space

**Comment by shlapkov** [comment]
the same steps with 2.0.10 working fine.

**Comment by luigidellaquila** [comment]
Hi @shlapkov 

does it only happen when you migrate a db from 1.7.x?

**Comment by shlapkov** [comment]
Hello @luigidellaquila Looks like it happens only with DB in 1.7.x format. After creating DB in new format by running Export from 1.7.x and then Import into 2.0.x the same SQL is running fine no OOM observed. Class platform-Version contains only 6046 records.

**Comment by tglman** [comment]
Thanks @shlapkov,

we will investigate on that, is it fine for you now use export and import as workaround?

Thank you

**Comment by shlapkov** [comment]
No it is not acceptable. How can we use in production database server which is running OOM on simple SQL select statement against class with 6000 records?
I don’t like word “workaround” for almost any defect which we open against 2.0.x we are getting “workaround” fixes it is not acceptable. Do you know what the root cause for the issue is? Do you know how this issue affected other configurations? We need to find root cause for the issue and fix it accordingly not just putting some “workaround” fix which might break something else.

**Comment by lvca** [comment]
I agree we need to find the cause of it, specially if it's still in 2.0.13-SNAPSHOT.

**Comment by lvca** [comment]
Could you provide such small database zipped so we can easily reproduce the problem?

**Comment by tglman** [comment]
hi @shlapkov 
I tried to reproduce the problem following your steps with the OpenBeer database that has ~7000 vertex, with no success, will be really use full get a copy  of your database.

**Comment by shlapkov** [comment]
Hey @tglman sent db via email to @lvca he should be able download from our secure site.

**Comment by tglman** [comment]
Hi @shlapkov  reproduced, i'm investigating

**Comment by tglman** [comment]
Hi @shlapkov,

I found the problem and solved, it was due to some lazy loading during the fetch plan, the was loading and retaining in memory also the record from platform-VersionContents, that overall they have a size of few hundreds megabytes, that was causing the out of memory.

I fixed this in both 2.0.x, and develop, they fix will be out with the next version.

**Comment by shlapkov** [comment]
Hello Orient Support, Please do not close issues which we do not confirmed fixed. Once you will have fix in official build please provide build number and we will verify the fix. Based on our previews experience fix maybe not be provided or overwritten during some merge from development branch.  Reopening the issue.

**Comment by lvca** [comment]
@shlapkov In our workflow the issue is closed as soon as the bug is not reproducible anymore. This is to avoid zombie issues remained open because users didn't respond. We had hundreds of issues like this. So I'd say try 2.0.x branch, and in case the issue is not fixed, reopen it.

**Comment by shlapkov** [comment]
I disagree with this workflow and based on current experience it is definable not working. Normal support process is: Issue closed only if customer confirm it is fixed or did not response on you request for confirmation in few days. This issue is not fixed in any official build how can you close it? Even if I'll try try 2.0.x branch it maybe broken before you release the next build whatever next build number is.

**Comment by lvca** [comment]
We usually write test cases to avoid regression. In this case could be hard to write it, because the problem is not strictly functional. If you confirm the issue is closed we can release the 2.0.14 hotfix asap.

**Comment by shlapkov** [comment]
Hello @lvca there few other issues are still open even with 2.0.14 release we will be not able to use latest build. List of issues was provided on support@orientdb.com last week didn't get any response back.

**Comment by shlapkov** [comment]
Hello @lvca not able to verify with current 2.0.14-SNAPSHOT build I am getting exception when trying to create DB wit remote connections: jvm 1    | WrapperSimpleApp Error: Caused by: java.lang.IncompatibleClassChangeError: Expecting non-
static method com.orientechnologies.orient.core.index.OIndexManagerRemote.getDatabase()Lcom/orientec
hnologies/orient/core/db/ODatabaseDocumentInternal;
jvm 1    | WrapperSimpleApp Error:      at com.orientechnologies.orient.core.index.OIndexManagerRemo
te.createIndex(OIndexManagerRemote.java:63)
jvm 1    | WrapperSimpleApp Error:      at com.orientechnologies.orient.core.index.OIndexManagerProx
y.createIndex(OIndexManagerProxy.java:79)
jvm 1    | WrapperSimpleApp Error:      at com.orientechnologies.orient.core.metadata.schema.OClassI
mpl.createIndex(OClassImpl.java:1444)
jvm 1    | WrapperSimpleApp Error:      at com.orientechnologies.orient.core.metadata.schema.OClassI
mpl.createIndex(OClassImpl.java:1409)
jvm 1    | WrapperSimpleApp Error:      at com.orientechnologies.orient.core.metadata.schema.OClassI
mpl.createIndex(OClassImpl.java:1399)
jvm 1    | WrapperSimpleApp Error:      at com.orientechnologies.orient.core.metadata.schema.OClassI
mpl.createIndex(OClassImpl.java:1395)

**Comment by shlapkov** [comment]
With plocal no issue to create db

**Comment by shlapkov** [comment]
Hello @lvca, sorry issue with IncompatibleClassChangeError appears to be related to my local repository. Please ignore this comment. After clean rebuild yes I can confirm issue is fixed with 2.0.14-SNAPSHOT however, I'll verify one more time with official 2.0.14 build.

**Comment by jillray7** [comment]
@shlapkov If there is an official with the official 2.0.14 build, please reopen this issue and let us know the details.
