### ISSUE TITLE
Suggestions how to track down or solve memory leakage problem on OrientDb

### ISSUE THREAD

**Issue by sepetukas** [orientechnologies/orientdb#4807]
We have OrientDB  version 2.1.0 in production (before were other versions starting from 2.0.8). 
Db is used as follows:
 4 to  5 remote clients are continuously pushing data to the database. 
There are around 88k inserts in hour. Records older then some date are deleted every 10 min.
The problem is that OrientDB eats all the ram (16 Gbytes) in about 4 days. Heap consumption is quite stable around 800 MB. So my guess would be that the problem is with the native memory leakage.

Any suggestions how to solve this problem?

**Comment by sepetukas** [comment]
It looks like the memory leakage is related with records deletion (only inserts and deletion queries are executed on the database right now). The code below is executed every 10 min.
```java
try {
  graph = getGraph().getFactory().getTx();
  Integer res = graph.command(new OCommandSQL("delete vertex AuditVertex where createdOn > ? and createdOn < ?")).execute( fromDate, toDate);
} finally {
   if (graph != null) {
     graph.shutdown();
   }
 }
```

Any ideas?

**Comment by laa** [comment]
Hi,
Waht is you settings, also OrientDB uses whole memory to use it for data
caching.
Do you have additional memory grow aftter 16 GB or it keeps stable on this
level ?

**Comment by sepetukas** [comment]
Hi there,
the settings are:
```
-Xmx2g
-Djna.nosys=true
-XX:+HeapDumpOnOutOfMemoryError
-Djava.awt.headless=true
-Dfile.encoding=UTF8
-Drhino.opt.level=9
-Dprofiler.enabled=true
-Dstorage.diskCache.bufferSize=8192
```
orientdb-server-config.xml is default

before we stored xml files in Orientdb together with relations between them. In such case it took about one week to consume all swap space and crash. Now we store only relations in orientDB and restart it every 24h to free some memory for mongodb (witch runs on the same machine) so I can not say what is happening after all ram is used.
How to prevent orient from using all RAM for caching? 
In any way I will try to monitor this issue and maybe use separate machine for orient to track down the problem

**Comment by laa** [comment]
Funny, you are the first user who has such issue.
Could you open JMX console , find bean com.orientechnologies.orient.core.storage.cache.local:type=O2QCacheMXBean and send value of parameter usedMemoryInGB when oreintdb consumes memory ?

**Comment by sepetukas** [comment]
Yes it is funny and makes me wonder that I don't understand something. Now db uses around 6GB of ram and O2QCacheMXBean shows 3.61GB. It is strange that this number increases every time deletion procedure is made. 
In any way I've ordered new machine dedicated only to orientdb and will run the instance for longer time to check the behavior. Will come back with new info

**Comment by sepetukas** [comment]
Some update: now orientdb runs on dedicated machine which has 16GB of RAM, 8 GB of swap. After 10 days I have 92% of RAM occupied and already 2 GB of swap is used. O2QCacheMXBean.UsedMemoryInGB= 6.8.

I have no doubt that after one week i will get out of memory exception.
I would be very grateful for any ideas how to overcome this

**Comment by laa** [comment]
ok, what is size of write cache you find JMX bean for  one there too , what is disk cache size ? 
Could you send me heap dump so I will inspect it ?

**Comment by sepetukas** [comment]
OWOWCacheMXBean WriteCacheSize = -1049

Info from LOCAL SERVER CONFIGURATION (not sure where to find disk cache size)

dump will send you by email

 storage.diskCache.bufferSize                           | 13472                     |
| storage.diskCache.writeCachePart                       | 15                        |
| storage.diskCache.writeCachePageTTL                    | 86400                     |
| storage.diskCache.writeCachePageFlushInterval          | 25                        |
| storage.diskCache.writeCacheFlushInactivityInterval    | 60000                     |
| storage.diskCache.writeCacheFlushLockTimeout           | -1                        |
| storage.diskCache.diskFreeSpaceLimit                   | 100                       |
| storage.diskCache.diskFreeSpaceCheckInterval           | 5                         |
| storage.configuration.syncOnUpdate                     | true                      |
| storage.compressionMethod                              | nothing                   |
| storage.useWAL                                         | true                      |
| storage.wal.syncOnPageFlush                            | true                      |
| storage.wal.cacheSize                                  | 3000                      |
| storage.wal.maxSegmentSize                             | 128                       |
| storage.wal.maxSize                                    | 4096                      |
| storage.wal.commitTimeout                              | 1000                      |
| storage.wal.shutdownTimeout                            | 10000                     |
| storage.wal.fuzzyCheckpointInterval                    | 300                       |
| storage.wal.reportAfterOperationsDuringRestore         | 10000                     |
| storage.wal.restore.batchSize                          | 50000                     |
| storage.wal.readCacheSize                              | 1000                      |
| storage.wal.fuzzyCheckpointShutdownWait                | 600                       |
| storage.wal.fullCheckpointShutdownTimeout              | 600

**Comment by laa** [comment]
Hi, could you do following (*do not do both of those steps together*, perform one step then another one) 

1. disable WAL for a while and track memory usage. -Dstorage.useWAL=false.
2. Apply this patch - https://www.dropbox.com/s/8aw9ybs3xmld42s/free_direct_memry_during_finalize.patch?dl=0


Please let me know if one of those steps fixed your problem.

**Comment by laa** [comment]
Please wait for an hour I will provide distribution with memory leak detector ).

**Comment by laa** [comment]
Hi, could you do following:
1. Download this distribution https://www.dropbox.com/s/9wed2j5iowb4cv0/orientdb-community-2.2.0-SNAPSHOT-distribution.zip?dl=0
2. Set property -Dmemory.directMemory.trackMode=true
3. Open JMX console and connect to direct memory bean.
4. Subscribe to notifications.
5. Leave console open till notifications about detected memory leaks will be fired.
6. Sent stack trace of method where memory from memory leak was allocated (it will be in userData field) in separate gist.

**Comment by laa** [comment]
Issue was closed because of no reply please feel free to reopen this issue.

**Comment by sepetukas** [comment]
Sorry for late response. Was busy + email notifications did not reach me.
Today OrientDb crashed after about 4 weeks of continuous work. It was killed by the Linux kernel, not JVM.
I do not think that memory leak detection based on JVM will help here.
If you think that i need to try it with your memory leak detector let me know

**Comment by laa** [comment]
Hi,

Sure, could you try latest version of develop branch and check memory leaks
as I described.

On Tue, Oct 27, 2015 at 5:24 PM sepetukas <notifications@github.com> wrote:

> Sorry for late response. Was busy + email notifications did not reach me.
> Today OrientDb crashed after about 4 weeks of continuous work. It was
> killed by the Linux kernel, not JVM.
> I do not think that memory leak detection based on JVM will help here.
> If you think that i need to try it with your memory leak detector let me
> know
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/4807#issuecomment-151539523>
> .
>
-- 
Best regards,
Andrey Lomakin, R&D lead.
twitter:@Andrey_Lomakin linkedin:https://ua.linkedin.com/in/andreylomakin

Orient Technologies
the Company behind OrientDB

**Comment by laa** [comment]
BTW funny but you are the only person who has such kind of issue.
Have you noticed any exceptions in server log ?

On Wed, Oct 28, 2015 at 7:49 AM Andrey Lomakin <lomakin.andrey@gmail.com>
wrote:

> Hi,
>
> Sure, could you try latest version of develop branch and check memory
> leaks as I described.
>
> On Tue, Oct 27, 2015 at 5:24 PM sepetukas <notifications@github.com>
> wrote:
>
>> Sorry for late response. Was busy + email notifications did not reach me.
>> Today OrientDb crashed after about 4 weeks of continuous work. It was
>> killed by the Linux kernel, not JVM.
>> I do not think that memory leak detection based on JVM will help here.
>> If you think that i need to try it with your memory leak detector let me
>> know
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/orientechnologies/orientdb/issues/4807#issuecomment-151539523>
>> .
>>
> --
> Best regards,
> Andrey Lomakin, R&D lead.
> twitter:@Andrey_Lomakin linkedin:https://ua.linkedin.com/in/andreylomakin
>
> Orient Technologies
> the Company behind OrientDB
>
-- 
Best regards,
Andrey Lomakin, R&D lead.
twitter:@Andrey_Lomakin linkedin:https://ua.linkedin.com/in/andreylomakin

Orient Technologies
the Company behind OrientDB

**Comment by sepetukas** [comment]
Hi,

no exceptions on server log.

I will try latest branch, just not sure when. Hopefully next week

**Comment by sepetukas** [comment]
Hello again, 
I've tried to run last version of dev branch but hit the problem with the exception 
```
 Exception in audit Storage:
com.orientechnologies.orient.enterprise.channel.binary.OResponseProcessingException: Exception during response processing.
        at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.throwSerializedException(OChannelBinaryAsynchClient.java:445) ~[orientdb-enterprise-2.1.0.jar:2.1.0]
        at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.handleStatus(OChannelBinaryAsynchClient.java:400) ~[orientdb-enterprise-2.1.0.jar:2.1.0]
        at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:282) ~[orientdb-enterprise-2.1.0.jar:2.1.0]
        at com.orientechnologies.orient.enterprise.channel.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:171) ~[orientdb-enterprise-2.1.0.jar:2.1.0]
        at com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:2136) ~[orientdb-client-2.1.0.jar:2.1.0]
        at com.orientechnologies.orient.client.remote.OStorageRemote.openRemoteDatabase(OStorageRemote.java:1864) ~[orientdb-client-2.1.0.jar:2.1.0]
        at com.orientechnologies.orient.client.remote.OStorageRemote.open(OStorageRemote.java:222) ~[orientdb-client-2.1.0.jar:2.1.0]
        at com.orientechnologies.orient.client.remote.OStorageRemoteThread.open(OStorageRemoteThread.java:89) ~[orientdb-client-2.1.0.jar:2.1.0]
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:249) ~[orientdb-core-2.1.0.jar:2.1.0]
        at com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPolled.internalOpen(OPartitionedDatabasePool.java:140) ~[orientdb-core-2.1.0.jar:2.1.0]
        at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.openDatabase(OPartitionedDatabasePool.java:340) ~[orientdb-core-2.1.0.jar:2.1.0]
        at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.acquire(OPartitionedDatabasePool.java:313) ~[orientdb-core-2.1.0.jar:2.1.0]
        at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.<init>(OrientBaseGraph.java:154) ~[orientdb-graphdb-2.1.0.jar:2.1.0]
        at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.<init>(OrientTransactionalGraph.java:77) ~[orientdb-graphdb-2.1.0.jar:2.1.0]
        at com.tinkerpop.blueprints.impls.orient.OrientGraph.<init>(OrientGraph.java:128) ~[orientdb-graphdb-2.1.0.jar:2.1.0]
        at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.getTx(OrientGraphFactory.java:74) ~[orientdb-graphdb-2.1.0.jar:2.1.0]
        at lt.ambernet.proxybet.common.internal.auditing.AuditVertexToGraphDb.getGraph(AuditVertexToGraphDb.java:114) ~[lt.ambernet.proxybet.common-1.0-SNAPSHOT.jar:?]
        at lt.ambernet.proxybet.common.internal.auditing.AuditVertexToGraphDb.saveAuditVertex(AuditVertexToGraphDb.java:78) ~[lt.ambernet.proxybet.common-1.0-SNAPSHOT.jar:?]
        at lt.ambernet.proxybet.common.internal.auditing.AuditingStorageTask.run(AuditingStorageTask.java:76) [lt.ambernet.proxybet.common-1.0-SNAPSHOT.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_40]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_40]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_40]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_40]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]
Caused by: java.lang.NullPointerException
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.openDatabase(ONetworkProtocolBinary.java:806) ~[?:?]
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:341) ~[?:?]
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:216) ~[?:?]
```
I have 5 instances which connects to the DB. Fails not all but only some. When failing it causes a lot of open connections (program is retrying to connect constantly) event if I have some pseudo code as follows 
```
try{
  orientFactory.getTx();
//do stuff
}finally{
   orientFactory.close()
}
```
Using orient-db-core-2.1.5.jar does not help

**Comment by laa** [comment]
@tglman  could look at issue ?

**Comment by tglman** [comment]
Hi @sepetukas,

Are the client and the server of the same version ? i think nope, we still doing some compatibility testing, i just commited a fix that should fix that exception.

**Comment by lvca** [comment]
@sepetukas Could you also try last GA? 2.1.5.

**Comment by sepetukas** [comment]
Hi, my prod environment uses GA 2.1.5 and clients are 2.1.0 I had no
problems so far

**Comment by sepetukas** [comment]
Hi, found time to try last orientDB version 2.2.0.. but still have problems to connect to the db with driver version 2.1.5.
Exception on client side:
```
com.orientechnologies.orient.core.exception.ODatabaseException: Cannot open database url=remote:orientdb.duok5.tv/auditDB2
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:285) ~[orientdb-core-2.1.5.jar:2.1.5]
        at com.orientechnologies.orient.core.db.OPartitionedDatabasePool$DatabaseDocumentTxPolled.internalOpen(OPartitionedDatabasePool.java:140) ~[orientdb-core-2.1.5.jar:2.1.5]
        at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.openDatabase(OPartitionedDatabasePool.java:340) ~[orientdb-core-2.1.5.jar:2.1.5]
        at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.acquire(OPartitionedDatabasePool.java:313) ~[orientdb-core-2.1.5.jar:2.1.5]
        at com.tinkerpop.blueprints.impls.orient.OrientBaseGraph.<init>(OrientBaseGraph.java:154) ~[orientdb-graphdb-2.1.5.jar:2.1.5]
        at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.<init>(OrientTransactionalGraph.java:77) ~[orientdb-graphdb-2.1.5.jar:2.1.5]
        at com.tinkerpop.blueprints.impls.orient.OrientGraph.<init>(OrientGraph.java:128) ~[orientdb-graphdb-2.1.5.jar:2.1.5]
        at com.tinkerpop.blueprints.impls.orient.OrientGraphFactory.getTx(OrientGraphFactory.java:74) ~[orientdb-graphdb-2.1.5.jar:2.1.5]
        at lt.ambernet.proxybet.common.internal.auditing.AuditVertexToGraphDb.getGraph(AuditVertexToGraphDb.java:114) ~[lt.ambernet.proxybet.common-1.0-SNAPSHOT.jar:?]
        at lt.ambernet.proxybet.common.internal.auditing.AuditVertexToGraphDb.saveAuditVertex(AuditVertexToGraphDb.java:78) ~[lt.ambernet.proxybet.common-1.0-SNAPSHOT.jar:?]
        at lt.ambernet.proxybet.common.internal.auditing.AuditingStorageTask.run(AuditingStorageTask.java:76) [lt.ambernet.proxybet.common-1.0-SNAPSHOT.jar:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_40]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_40]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_40]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_40]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_40]
Caused by: java.lang.NullPointerException: Name is null
        at java.lang.Enum.valueOf(Enum.java:236) ~[?:1.8.0_40]
        at com.orientechnologies.orient.core.config.OStorageClusterConfiguration$STATUS.valueOf(OStorageClusterConfiguration.java:24) ~[?:?]
        at com.orientechnologies.orient.core.config.OStorageConfiguration.fromStream(OStorageConfiguration.java:257) ~[?:?]
        at com.orientechnologies.orient.core.config.OStorageConfiguration.load(OStorageConfiguration.java:132) ~[?:?]
        at com.orientechnologies.orient.client.remote.OStorageRemote.open(OStorageRemote.java:226) ~[?:?]
        at com.orientechnologies.orient.client.remote.OStorageRemoteThread.open(OStorageRemoteThread.java:89) ~[?:?]
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.open(ODatabaseDocumentTx.java:252) ~[?:?]
```
Is there any way you will fix this or I should use driver 2.2.0 on client side? I have 5 clients and if I'll upgrade all of them to 2.2.0 version will they work with server 2.1.5?

**Comment by lvca** [comment]
You cannot open the database back from 2.1.x if has been opened with 2.2.0 (major)

**Comment by laa** [comment]
Hi, do you have hash indexes in your database ?

**Comment by sepetukas** [comment]
Hi,
no I do not have. All indexes are SB-tree

**Comment by laa** [comment]
That is strange,
Any way we have found memory leak issue in disk cache which will be fixed
in couple of days.
If you would test it, it will be cool.

BTW could you make heap dump and send it to me next time you will have
problem with memory consumption ?

On Mon, Nov 23, 2015 at 5:09 PM sepetukas <notifications@github.com> wrote:

> Hi,
> no I do not have. All indexes are SB-tree
>
> On 23 November 2015 at 11:36, Andrey Lomakin <notifications@github.com>
> wrote:
>
> > Hi, do you have hash indexes in your database ?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/orientechnologies/orientdb/issues/4807#issuecomment-158887798
> >
> > .
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/4807#issuecomment-158963346>
> .
>
-- 
Best regards,
Andrey Lomakin, R&D lead.
OrientDB Ltd

twitter:@Andrey_Lomakin linkedin:https://ua.linkedin.com/in/andreylomakin

**Comment by sepetukas** [comment]
Hi, I've send heap dump to your personal email.
 I get this `INFO  {db=auditDB2} Max cache limit is reached (3000 vs.
3066), sync flush is performed [ODiskWriteAheadLog$LogSegment]` quite often.
Hope this memory leak issue you found is related with this message

**Comment by laa** [comment]
I think I will backport memory leak detection mechanics to 2.1.x and will send you distribution. It will take couple of days though.

**Comment by laa** [comment]
Hi Could you try this build https://drive.google.com/file/d/0B2oZq2xVp841amlpOWtOMzkwejg/view?usp=sharing .

To switch on memory leak detection mechanics could you set 
property -Dmemory.directMemory.trackMode=true and check log whether memory leaks are detected ?

**Comment by sepetukas** [comment]
Hi, I switched to version 2.1.7... not sure if this related but:

`
com.orientechnologies.orient.core.index.OIndexException: Error during
removal of entry by key
        at
com.orientechnologies.orient.core.index.OIndexMultiValues.remove(OIndexMultiValues.java:218)
~[orientdb-core-2.1.5.jar:2.1.5]
        at
com.orientechnologies.orient.core.index.OIndexAbstract.removeFromSnapshot(OIndexAbstract.java:970)
~[orientdb-core-2.1.5.jar:2.1.5]
        at
com.orientechnologies.orient.core.index.OIndexAbstract.applyIndexTxEntry(OIndexAbstract.java:1156)
~[orientdb-core-2.1.5.jar:2.1.5]
        at
com.orientechnologies.orient.core.index.OIndexAbstract.addTxOperation(OIndexAbstract.java:762)
~[orientdb-core-2.1.5.jar:2.1.5]
        at
com.orientechnologies.orient.core.tx.OTransactionOptimistic$CommitIndexesCallback.run(OTransactionOptimistic.java:101)
~[orientdb-core-2.1.5.jar:2.1.5]
        at
com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:1211)
~[orientdb-core-2.1.5.jar:2.1.5]
        at
com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:606)
~[orientdb-core-2.1.5.jar:2.1.5]
        at
com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:156)
~[orientdb-core-2.1.5.jar:2.1.5]
        at
com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2689)
~[orientdb-core-2.1.5.jar:2.1.5]
        at
com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2658)
~[orientdb-core-2.1.5.jar:2.1.5]
        at
com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.commit(OrientTransactionalGraph.java:161)
~[orientdb-graphdb-2.1.5.jar:2.1.5]
        at
com.orientechnologies.orient.graph.sql.OCommandExecutorSQLDeleteVertex.result(OCommandExecutorSQLDeleteVertex.java:247)
~[orientdb-graphdb-2.1.5.jar:2.1.5]
        at
com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.pushResult(OCommandExecutorSQLResultsetAbstract.java:267)
~[orientdb-core-2.1.5.jar:2.1.5]
        at
com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.addResult(OCommandExecutorSQLSelect.java:669)
~[orientdb-core-2.1.5.jar:2.1.5]
        at
com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.handleResult(OCommandExecutorSQLSelect.java:576)
~[orientdb-core-2.1.5.jar:2.1.5]
        at
com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearchRecord(OCommandExecutorSQLSelect.java:538)
~[orientdb-core-2.1.5.jar:2.1.5]
        at
com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.fetchFromTarget(OCommandExecutorSQLSelect.java:1437)
~[orientdb-core-2.1.5.jar:2.1.5]
        at
com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.fetchValuesFromIndexCursor(OCommandExecutorSQLSelect.java:2061)
~[orientdb-core-2.1.5.jar:2.1.5]
        at
com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchForIndexes(OCommandExecutorSQLSelect.java:1934)
~[orientdb-core-2.1.5.jar:2.1.5]
        at
com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchInClasses(OCommandExecutorSQLSelect.java:879)
~[orientdb-core-2.1.5.jar:2.1.5]
        at
com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.assignTarget(OCommandExecutorSQLResultsetAbstract.java:199)
~[orientdb-core-2.1.5.jar:2.1.5]
        at
com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.assignTarget(OCommandExecutorSQLSelect.java:474)
~[orientdb-core-2.1.5.jar:2.1.5]
        at
com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCommandExecutorSQLSelect.java:456)
~[orientdb-core-2.1.5.jar:2.1.5]
        at
com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:427)
~[orientdb-core-2.1.5.jar:2.1.5]
        at
com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:90)
~[orientdb-core-2.1.5.jar:2.1.5]
        at
com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1547)
~[orientdb-core-2.1.5.jar:2.1.5]
        at
com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1528)
~[orientdb-core-2.1.5.jar:2.1.5]
        at
com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:72)
~[orientdb-core-2.1.5.jar:2.1.5]
        at
com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33)
~[orientdb-core-2.1.5.jar:2.1.5]
        at
com.orientechnologies.orient.graph.sql.OCommandExecutorSQLDeleteVertex$2.call(OCommandExecutorSQLDeleteVertex.java:213)
~[orientdb-graphdb-2.1.5.jar:2.1.5]
        at
com.orientechnologies.orient.graph.sql.OCommandExecutorSQLDeleteVertex$2.call(OCommandExecutorSQLDeleteVertex.java:207)
~[orientdb-graphdb-2.1.5.jar:2.1.5]
        at
com.orientechnologies.orient.graph.sql.OGraphCommandExecutorSQLFactory.runInTx(OGraphCommandExecutorSQLFactory.java:169)
~[orientdb-graphdb-2.1.5.jar:2.1.5]
        at
com.orientechnologies.orient.graph.sql.OGraphCommandExecutorSQLFactory.runInConfiguredTxMode(OGraphCommandExecutorSQLFactory.java:254)
~[orientdb-graphdb-2.1.5.jar:2.1.5]
        at
com.orientechnologies.orient.graph.sql.OCommandExecutorSQLDeleteVertex.execute(OCommandExecutorSQLDeleteVertex.java:207)
~[orientdb-graphdb-2.1.5.jar:2.1.5]
        at
com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:90)
~[orientdb-core-2.1.5.jar:2.1.5]
        at
com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1547)
~[orientdb-core-2.1.5.jar:2.1.5]
        at
com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1528)
~[orientdb-core-2.1.5.jar:2.1.5]
        at
com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:67)
~[orientdb-core-2.1.5.jar:2.1.5]
        at
com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1323)
~[?:?]
        at
com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:400)
~[?:?]
        at
com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:223)
~[?:?]
        at
com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
~[orientdb-core-2.1.5.jar:2.1.5]
Caused by:
com.orientechnologies.common.directmemory.ODirectMemoryViolationException:
Last position of provided data interval [14603148] is more than size of
allocated area [65552]
        at
com.orientechnologies.common.directmemory.OTrackedDirectMemoryPointer.rangeCheck(OTrackedDirectMemoryPointer.java:225)
~[?:?]
        at
com.orientechnologies.common.directmemory.OTrackedDirectMemoryPointer.get(OTrackedDirectMemoryPointer.java:56)
~[?:?]
        at
com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OWALChangesTree.getBinaryValue(OWALChangesTree.java:48)
~[orientdb-core-2.1.5.jar:2.1.5]
        at
com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OWALChangesTree$PointerWrapper.get(OWALChangesTree.java:791)
~[orientdb-core-2.1.5.jar:2.1.5]
        at
com.orientechnologies.common.serialization.types.OStringSerializer.deserializeFromDirectMemoryObject(OStringSerializer.java:163)
~[orientdb-core-2.1.5.jar:2.1.5]
        at
com.orientechnologies.common.serialization.types.OStringSerializer.deserializeFromDirectMemoryObject(OStringSerializer.java:32)
~[orientdb-core-2.1.5.jar:2.1.5]
        at
com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.deserializeFromDirectMemory(ODurablePage.java:129)
~[orientdb-core-2.1.5.jar:2.1.5]
        at
com.orientechnologies.orient.core.index.sbtree.local.OSBTreeBucket.getKey(OSBTreeBucket.java:236)
~[orientdb-core-2.1.5.jar:2.1.5]
        at
com.orientechnologies.orient.core.index.sbtree.local.OSBTreeBucket.find(OSBTreeBucket.java:131)
~[orientdb-core-2.1.5.jar:2.1.5]
        at
com.orientechnologies.orient.core.index.sbtree.local.OSBTree.findBucket(OSBTree.java:1517)
~[orientdb-core-2.1.5.jar:2.1.5]
        at
com.orientechnologies.orient.core.index.sbtree.local.OSBTree.get(OSBTree.java:174)
~[orientdb-core-2.1.5.jar:2.1.5]
        at
com.orientechnologies.orient.core.index.engine.OSBTreeIndexEngine.get(OSBTreeIndexEngine.java:212)
~[orientdb-core-2.1.5.jar:2.1.5]
        at
com.orientechnologies.orient.core.index.OIndexMultiValues.remove(OIndexMultiValues.java:194)
~[orientdb-core-2.1.5.jar:2.1.5]

`

another warning is:
`
WARNI {db=auditDB2} Page in file flowsto.pcl with index 19326 was placed in
wrong free list, this error will be fixed automatically. [OPaginatedCluster]
`
I am sure this is not something serious but would be nice to know what is
wrong

**Comment by sepetukas** [comment]
Hi, I switched to version 2.1.7... not sure if this related but:
```
com.orientechnologies.orient.core.index.OIndexException: Error during removal of entry by key
        at com.orientechnologies.orient.core.index.OIndexMultiValues.remove(OIndexMultiValues.java:218) ~[orientdb-core-2.1.5.jar:2.1.5]
        at com.orientechnologies.orient.core.index.OIndexAbstract.removeFromSnapshot(OIndexAbstract.java:970) ~[orientdb-core-2.1.5.jar:2.1.5]
        at com.orientechnologies.orient.core.index.OIndexAbstract.applyIndexTxEntry(OIndexAbstract.java:1156) ~[orientdb-core-2.1.5.jar:2.1.5]
        at com.orientechnologies.orient.core.index.OIndexAbstract.addTxOperation(OIndexAbstract.java:762) ~[orientdb-core-2.1.5.jar:2.1.5]
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic$CommitIndexesCallback.run(OTransactionOptimistic.java:101) ~[orientdb-core-2.1.5.jar:2.1.5]
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:1211) ~[orientdb-core-2.1.5.jar:2.1.5]
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:606) ~[orientdb-core-2.1.5.jar:2.1.5]
        at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:156) ~[orientdb-core-2.1.5.jar:2.1.5]
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2689) ~[orientdb-core-2.1.5.jar:2.1.5]
        at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2658) ~[orientdb-core-2.1.5.jar:2.1.5]
        at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.commit(OrientTransactionalGraph.java:161) ~[orientdb-graphdb-2.1.5.jar:2.1.5]
        at com.orientechnologies.orient.graph.sql.OCommandExecutorSQLDeleteVertex.result(OCommandExecutorSQLDeleteVertex.java:247) ~[orientdb-graphdb-2.1.5.jar:2.1.5]
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.pushResult(OCommandExecutorSQLResultsetAbstract.java:267) ~[orientdb-core-2.1.5.jar:2.1.5]
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.addResult(OCommandExecutorSQLSelect.java:669) ~[orientdb-core-2.1.5.jar:2.1.5]
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.handleResult(OCommandExecutorSQLSelect.java:576) ~[orientdb-core-2.1.5.jar:2.1.5]
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearchRecord(OCommandExecutorSQLSelect.java:538) ~[orientdb-core-2.1.5.jar:2.1.5]
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.fetchFromTarget(OCommandExecutorSQLSelect.java:1437) ~[orientdb-core-2.1.5.jar:2.1.5]
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.fetchValuesFromIndexCursor(OCommandExecutorSQLSelect.java:2061) ~[orientdb-core-2.1.5.jar:2.1.5]
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchForIndexes(OCommandExecutorSQLSelect.java:1934) ~[orientdb-core-2.1.5.jar:2.1.5]
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchInClasses(OCommandExecutorSQLSelect.java:879) ~[orientdb-core-2.1.5.jar:2.1.5]
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.assignTarget(OCommandExecutorSQLResultsetAbstract.java:199) ~[orientdb-core-2.1.5.jar:2.1.5]
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.assignTarget(OCommandExecutorSQLSelect.java:474) ~[orientdb-core-2.1.5.jar:2.1.5]
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCommandExecutorSQLSelect.java:456) ~[orientdb-core-2.1.5.jar:2.1.5]
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:427) ~[orientdb-core-2.1.5.jar:2.1.5]
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:90) ~[orientdb-core-2.1.5.jar:2.1.5]
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1547) ~[orientdb-core-2.1.5.jar:2.1.5]
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1528) ~[orientdb-core-2.1.5.jar:2.1.5]
        at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:72) ~[orientdb-core-2.1.5.jar:2.1.5]
        at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33) ~[orientdb-core-2.1.5.jar:2.1.5]
        at com.orientechnologies.orient.graph.sql.OCommandExecutorSQLDeleteVertex$2.call(OCommandExecutorSQLDeleteVertex.java:213) ~[orientdb-graphdb-2.1.5.jar:2.1.5]
        at com.orientechnologies.orient.graph.sql.OCommandExecutorSQLDeleteVertex$2.call(OCommandExecutorSQLDeleteVertex.java:207) ~[orientdb-graphdb-2.1.5.jar:2.1.5]
        at com.orientechnologies.orient.graph.sql.OGraphCommandExecutorSQLFactory.runInTx(OGraphCommandExecutorSQLFactory.java:169) ~[orientdb-graphdb-2.1.5.jar:2.1.5]
        at com.orientechnologies.orient.graph.sql.OGraphCommandExecutorSQLFactory.runInConfiguredTxMode(OGraphCommandExecutorSQLFactory.java:254) ~[orientdb-graphdb-2.1.5.jar:2.1.5]
        at com.orientechnologies.orient.graph.sql.OCommandExecutorSQLDeleteVertex.execute(OCommandExecutorSQLDeleteVertex.java:207) ~[orientdb-graphdb-2.1.5.jar:2.1.5]
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:90) ~[orientdb-core-2.1.5.jar:2.1.5]
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1547) ~[orientdb-core-2.1.5.jar:2.1.5]
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1528) ~[orientdb-core-2.1.5.jar:2.1.5]
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:67) ~[orientdb-core-2.1.5.jar:2.1.5]
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1323) ~[?:?]
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:400) ~[?:?]
        at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:223) ~[?:?]
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77) ~[orientdb-core-2.1.5.jar:2.1.5]
Caused by: com.orientechnologies.common.directmemory.ODirectMemoryViolationException: Last position of provided data interval [14603148] is more than size of allocated area [65552]
        at com.orientechnologies.common.directmemory.OTrackedDirectMemoryPointer.rangeCheck(OTrackedDirectMemoryPointer.java:225) ~[?:?]
        at com.orientechnologies.common.directmemory.OTrackedDirectMemoryPointer.get(OTrackedDirectMemoryPointer.java:56) ~[?:?]
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OWALChangesTree.getBinaryValue(OWALChangesTree.java:48) ~[orientdb-core-2.1.5.jar:2.1.5]
        at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OWALChangesTree$PointerWrapper.get(OWALChangesTree.java:791) ~[orientdb-core-2.1.5.jar:2.1.5]
        at com.orientechnologies.common.serialization.types.OStringSerializer.deserializeFromDirectMemoryObject(OStringSerializer.java:163) ~[orientdb-core-2.1.5.jar:2.1.5]
        at com.orientechnologies.common.serialization.types.OStringSerializer.deserializeFromDirectMemoryObject(OStringSerializer.java:32) ~[orientdb-core-2.1.5.jar:2.1.5]
        at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.deserializeFromDirectMemory(ODurablePage.java:129) ~[orientdb-core-2.1.5.jar:2.1.5]
        at com.orientechnologies.orient.core.index.sbtree.local.OSBTreeBucket.getKey(OSBTreeBucket.java:236) ~[orientdb-core-2.1.5.jar:2.1.5]
        at com.orientechnologies.orient.core.index.sbtree.local.OSBTreeBucket.find(OSBTreeBucket.java:131) ~[orientdb-core-2.1.5.jar:2.1.5]
        at com.orientechnologies.orient.core.index.sbtree.local.OSBTree.findBucket(OSBTree.java:1517) ~[orientdb-core-2.1.5.jar:2.1.5]
        at com.orientechnologies.orient.core.index.sbtree.local.OSBTree.get(OSBTree.java:174) ~[orientdb-core-2.1.5.jar:2.1.5]
        at com.orientechnologies.orient.core.index.engine.OSBTreeIndexEngine.get(OSBTreeIndexEngine.java:212) ~[orientdb-core-2.1.5.jar:2.1.5]
        at com.orientechnologies.orient.core.index.OIndexMultiValues.remove(OIndexMultiValues.java:194) ~[orientdb-core-2.1.5.jar:2.1.5]
```

**Comment by laa** [comment]
Hi ,
I am sorry but you have to do export / import to fix the issue .
Could you do this and provide feedback how it will behave after that ?

On Thu, Dec 10, 2015, 16:37 sepetukas <notifications@github.com> wrote:

> Hi, I switched to version 2.1.7... not sure if this related but:
>
> com.orientechnologies.orient.core.index.OIndexException: Error during removal of entry by key
>         at com.orientechnologies.orient.core.index.OIndexMultiValues.remove(OIndexMultiValues.java:218) ~[orientdb-core-2.1.5.jar:2.1.5]
>         at com.orientechnologies.orient.core.index.OIndexAbstract.removeFromSnapshot(OIndexAbstract.java:970) ~[orientdb-core-2.1.5.jar:2.1.5]
>         at com.orientechnologies.orient.core.index.OIndexAbstract.applyIndexTxEntry(OIndexAbstract.java:1156) ~[orientdb-core-2.1.5.jar:2.1.5]
>         at com.orientechnologies.orient.core.index.OIndexAbstract.addTxOperation(OIndexAbstract.java:762) ~[orientdb-core-2.1.5.jar:2.1.5]
>         at com.orientechnologies.orient.core.tx.OTransactionOptimistic$CommitIndexesCallback.run(OTransactionOptimistic.java:101) ~[orientdb-core-2.1.5.jar:2.1.5]
>         at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.commit(OAbstractPaginatedStorage.java:1211) ~[orientdb-core-2.1.5.jar:2.1.5]
>         at com.orientechnologies.orient.core.tx.OTransactionOptimistic.doCommit(OTransactionOptimistic.java:606) ~[orientdb-core-2.1.5.jar:2.1.5]
>         at com.orientechnologies.orient.core.tx.OTransactionOptimistic.commit(OTransactionOptimistic.java:156) ~[orientdb-core-2.1.5.jar:2.1.5]
>         at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2689) ~[orientdb-core-2.1.5.jar:2.1.5]
>         at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.commit(ODatabaseDocumentTx.java:2658) ~[orientdb-core-2.1.5.jar:2.1.5]
>         at com.tinkerpop.blueprints.impls.orient.OrientTransactionalGraph.commit(OrientTransactionalGraph.java:161) ~[orientdb-graphdb-2.1.5.jar:2.1.5]
>         at com.orientechnologies.orient.graph.sql.OCommandExecutorSQLDeleteVertex.result(OCommandExecutorSQLDeleteVertex.java:247) ~[orientdb-graphdb-2.1.5.jar:2.1.5]
>         at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.pushResult(OCommandExecutorSQLResultsetAbstract.java:267) ~[orientdb-core-2.1.5.jar:2.1.5]
>         at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.addResult(OCommandExecutorSQLSelect.java:669) ~[orientdb-core-2.1.5.jar:2.1.5]
>         at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.handleResult(OCommandExecutorSQLSelect.java:576) ~[orientdb-core-2.1.5.jar:2.1.5]
>         at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearchRecord(OCommandExecutorSQLSelect.java:538) ~[orientdb-core-2.1.5.jar:2.1.5]
>         at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.fetchFromTarget(OCommandExecutorSQLSelect.java:1437) ~[orientdb-core-2.1.5.jar:2.1.5]
>         at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.fetchValuesFromIndexCursor(OCommandExecutorSQLSelect.java:2061) ~[orientdb-core-2.1.5.jar:2.1.5]
>         at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchForIndexes(OCommandExecutorSQLSelect.java:1934) ~[orientdb-core-2.1.5.jar:2.1.5]
>         at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.searchInClasses(OCommandExecutorSQLSelect.java:879) ~[orientdb-core-2.1.5.jar:2.1.5]
>         at com.orientechnologies.orient.core.sql.OCommandExecutorSQLResultsetAbstract.assignTarget(OCommandExecutorSQLResultsetAbstract.java:199) ~[orientdb-core-2.1.5.jar:2.1.5]
>         at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.assignTarget(OCommandExecutorSQLSelect.java:474) ~[orientdb-core-2.1.5.jar:2.1.5]
>         at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.executeSearch(OCommandExecutorSQLSelect.java:456) ~[orientdb-core-2.1.5.jar:2.1.5]
>         at com.orientechnologies.orient.core.sql.OCommandExecutorSQLSelect.execute(OCommandExecutorSQLSelect.java:427) ~[orientdb-core-2.1.5.jar:2.1.5]
>         at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:90) ~[orientdb-core-2.1.5.jar:2.1.5]
>         at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1547) ~[orientdb-core-2.1.5.jar:2.1.5]
>         at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1528) ~[orientdb-core-2.1.5.jar:2.1.5]
>         at com.orientechnologies.orient.core.sql.query.OSQLQuery.run(OSQLQuery.java:72) ~[orientdb-core-2.1.5.jar:2.1.5]
>         at com.orientechnologies.orient.core.query.OQueryAbstract.execute(OQueryAbstract.java:33) ~[orientdb-core-2.1.5.jar:2.1.5]
>         at com.orientechnologies.orient.graph.sql.OCommandExecutorSQLDeleteVertex$2.call(OCommandExecutorSQLDeleteVertex.java:213) ~[orientdb-graphdb-2.1.5.jar:2.1.5]
>         at com.orientechnologies.orient.graph.sql.OCommandExecutorSQLDeleteVertex$2.call(OCommandExecutorSQLDeleteVertex.java:207) ~[orientdb-graphdb-2.1.5.jar:2.1.5]
>         at com.orientechnologies.orient.graph.sql.OGraphCommandExecutorSQLFactory.runInTx(OGraphCommandExecutorSQLFactory.java:169) ~[orientdb-graphdb-2.1.5.jar:2.1.5]
>         at com.orientechnologies.orient.graph.sql.OGraphCommandExecutorSQLFactory.runInConfiguredTxMode(OGraphCommandExecutorSQLFactory.java:254) ~[orientdb-graphdb-2.1.5.jar:2.1.5]
>         at com.orientechnologies.orient.graph.sql.OCommandExecutorSQLDeleteVertex.execute(OCommandExecutorSQLDeleteVertex.java:207) ~[orientdb-graphdb-2.1.5.jar:2.1.5]
>         at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:90) ~[orientdb-core-2.1.5.jar:2.1.5]
>         at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:1547) ~[orientdb-core-2.1.5.jar:2.1.5]
>         at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:1528) ~[orientdb-core-2.1.5.jar:2.1.5]
>         at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:67) ~[orientdb-core-2.1.5.jar:2.1.5]
>         at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1323) ~[?:?]
>         at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:400) ~[?:?]
>         at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:223) ~[?:?]
>         at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77) ~[orientdb-core-2.1.5.jar:2.1.5]
> Caused by: com.orientechnologies.common.directmemory.ODirectMemoryViolationException: Last position of provided data interval [14603148] is more than size of allocated area [65552]
>         at com.orientechnologies.common.directmemory.OTrackedDirectMemoryPointer.rangeCheck(OTrackedDirectMemoryPointer.java:225) ~[?:?]
>         at com.orientechnologies.common.directmemory.OTrackedDirectMemoryPointer.get(OTrackedDirectMemoryPointer.java:56) ~[?:?]
>         at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OWALChangesTree.getBinaryValue(OWALChangesTree.java:48) ~[orientdb-core-2.1.5.jar:2.1.5]
>         at com.orientechnologies.orient.core.storage.impl.local.paginated.wal.OWALChangesTree$PointerWrapper.get(OWALChangesTree.java:791) ~[orientdb-core-2.1.5.jar:2.1.5]
>         at com.orientechnologies.common.serialization.types.OStringSerializer.deserializeFromDirectMemoryObject(OStringSerializer.java:163) ~[orientdb-core-2.1.5.jar:2.1.5]
>         at com.orientechnologies.common.serialization.types.OStringSerializer.deserializeFromDirectMemoryObject(OStringSerializer.java:32) ~[orientdb-core-2.1.5.jar:2.1.5]
>         at com.orientechnologies.orient.core.storage.impl.local.paginated.base.ODurablePage.deserializeFromDirectMemory(ODurablePage.java:129) ~[orientdb-core-2.1.5.jar:2.1.5]
>         at com.orientechnologies.orient.core.index.sbtree.local.OSBTreeBucket.getKey(OSBTreeBucket.java:236) ~[orientdb-core-2.1.5.jar:2.1.5]
>         at com.orientechnologies.orient.core.index.sbtree.local.OSBTreeBucket.find(OSBTreeBucket.java:131) ~[orientdb-core-2.1.5.jar:2.1.5]
>         at com.orientechnologies.orient.core.index.sbtree.local.OSBTree.findBucket(OSBTree.java:1517) ~[orientdb-core-2.1.5.jar:2.1.5]
>         at com.orientechnologies.orient.core.index.sbtree.local.OSBTree.get(OSBTree.java:174) ~[orientdb-core-2.1.5.jar:2.1.5]
>         at com.orientechnologies.orient.core.index.engine.OSBTreeIndexEngine.get(OSBTreeIndexEngine.java:212) ~[orientdb-core-2.1.5.jar:2.1.5]
>         at com.orientechnologies.orient.core.index.OIndexMultiValues.remove(OIndexMultiValues.java:194) ~[orientdb-core-2.1.5.jar:2.1.5]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/4807#issuecomment-163640388>
> .
>
-- 
Best regards,
Andrey Lomakin, R&D lead.
OrientDB Ltd

twitter:@Andrey_Lomakin linkedin:https://ua.linkedin.com/in/andreylomakin

**Comment by sepetukas** [comment]
Hi, 
I was trying to make this new version (2.1.7) work few days. 
Problems:
1. I get ```SEVER Can not change cache size in runtime because storage engine plocal was not registered [OGlobalConfiguration$1]``` after server starts
2. I was not able to import my database. Exception is: GC overhead limit exceeded. Console is running with -Xmx2048m

maybe will try to increase Xmx even more

**Comment by sepetukas** [comment]
Orient 2.1.8, is up only 2 days, has about 8.5 million vertexes, always inserting and always deleting old ones. Memory consumption is:
Mem:  16359812k total, 16202776k used,   157036k free,     9656k buffers
Swap:  8388540k total,  6712544k used,  1675996k free,   837500k cached

ODirectMemoryMXBean has SIzein MB = 12750 and no notifications about memory leak

jemalloc result
![heap](https://cloud.githubusercontent.com/assets/12246849/12316307/d5b7b18c-ba8d-11e5-8eaa-25300ef4a81a.png)

will see if ti eventually OOM

**Comment by sepetukas** [comment]
So it crashed again..no errors .. nothing. Killed by the kernel. Did not last a week :)

**Comment by lvca** [comment]
Do you have VM in your OS? Can you activate it to avoid OS Kill? Also, could you allocate less DISKCACHE? let's say 20% less.

**Comment by laa** [comment]
HI,
We finished now new model of working with direct memory based on
ByteBuffers.
We will send you updated distribution next week.
Hope it will help to solve given problem.

On Fri, Jan 22, 2016 at 2:07 AM Luca Garulli <notifications@github.com>
wrote:

> Do you have VM in your OS? Can you activate it to avoid OS Kill? Also,
> could you allocate less DISKCACHE? let's say 20% less.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/4807#issuecomment-173755692>
> .
>
-- 
Best regards,
Andrey Lomakin, R&D lead.
OrientDB Ltd

twitter:@Andrey_Lomakin linkedin:https://ua.linkedin.com/in/andreylomakin

**Comment by machak** [comment]
haven't look into Orient implementation, this might be related:
http://www.evanjones.ca/java-bytebuffer-leak.html

**Comment by laa** [comment]
Hi guys,

Yes, we have already taken this into account in 2.2 version.


On Tue, Jan 26, 2016 at 1:40 PM marijan milicevic <notifications@github.com>
wrote:

> haven't look into Orient implementation, this might be related:
> http://www.evanjones.ca/java-bytebuffer-leak.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/orientechnologies/orientdb/issues/4807#issuecomment-174965769>
> .
>
-- 
Best regards,
Andrey Lomakin, R&D lead.
OrientDB Ltd

twitter:@Andrey_Lomakin linkedin:https://ua.linkedin.com/in/andreylomakin

**Comment by laa** [comment]
Hi, 
We provided new memory managament model specially to fix given issue.
Which may caused by 2 issues one in Linux core and one in JVM.
We will release betta soon.
So I hope it will resolve given issues.

**Comment by laa** [comment]
@sepetukas Did you have a chance to try it on 2.2 rc1 ?

**Comment by sepetukas** [comment]
Sorry but we moved away from OrientDb
