### ISSUE TITLE
Updates leaking across transactions in different threads

### ISSUE THREAD

**Issue by helgridly** [orientechnologies/orientdb#4922]
I've run into what seems to be a concurrency issue in OrientDB 2.1.1. The following series of steps shows data from one committed transaction leaking across to another transaction in a different thread that was previously opened:

1. Open a transaction T1.
2. Open another transaction T2 in a separate thread.
3. In T2, look up a vertex V1.
4. In T1, look up V1, and remove a vertex V2 connected to it with edge label "foo". Create V3 and make a new edge labelled "foo" from V1 to V3 instead.
5. Commit T1.
6. In T2, look for all edges named "foo" starting from V1.
7. T2 returns no "foo" edges out from V1. It seems to have picked up that V2-foo has been deleted, but doesn't know about the existence of V3-foo.

I've made a repro (in Scala) here: https://gist.github.com/helgridly/0c153a79fa746fa3e266

Is this a bug, or am I doing something wrong?

**Comment by dvoet** [comment]
Hi, I was wondering if there was any guidance on this issue. Is there a workaround? Is there and ETA for a fix or a patch that we can apply?

Thanks,
Doug

**Comment by laa** [comment]
Hi ,
Could you provide the same code in Java so I will look on it ?

**Comment by dvoet** [comment]
here ya go, thanks

https://gist.github.com/dvoet/199080751591ded5bf9b

**Comment by laa** [comment]
Hi,
I have found problem in this test:

You created test in assumption that threads never pauses and that Thread.sleep always sleep exactly the same time as it is specified. Both of these assumptions are not true, I modified test so it always guarantees order of events which  you described and this tests always pass. https://gist.github.com/laa/bf94ee5936cc95caef9b

Any way your test helped me to find one more problem, I pushed result. Could you check it ?

**Comment by dvoet** [comment]
If you move line 84 up 2 lines to above txCommitLatch.await() you will reproduce the error. The idea is that both threads get the vertex then t1 removes vertexes then t2 reads. Your code has t1 do its work then commit before t2 gets the vertex so there is not actually any concurrency.

**Comment by dvoet** [comment]
to be clear, my comment applies to your new test case. While the new code does guarantee the order of operations, the new order of operations is incorrect to reproduce the issue. Even though the code we posted is a little loose in enforcing order of operations it still shows a concurrency problem in orient. t2 should never see a vertex with no subordinates regardless of operation ordering, yet it does.

**Comment by laa** [comment]
Actually that is not a bug, I  will explain how all works there. When you read root vertex you read it with v2 vertex which is not deleted at the moment when you read record, but at the moment when you iterate over vertices, transaction which removes vertex has been already completed and we can not read this vertex as result we do not see any vertexes. 

It is so called phantom reads problem https://en.wikipedia.org/wiki/Isolation_(database_systems)#Phantom_reads . We use read committed serialization level and usage of serializable level is not reasonable so we do not have plans (now at least) to support it. Do you agree ?

**Comment by dvoet** [comment]
so rejiggering the locks so that the commit on t1 happens after t2 is done does indeed prevent the error so it seems phantom reads is the answer. Thanks for looking into it.

**Comment by laa** [comment]
Could you close issue then ?

**Comment by dvoet** [comment]
The person who opened it is on vacation, I don't have permissions to close it.

**Comment by laa** [comment]
I see, lets wait then, I will remove milestone from this issue.

**Comment by helgridly** [comment]
Closing as requested.
