### ISSUE TITLE
Update two vertex in batch mode leads to wrong result

### ISSUE THREAD

**Issue by StarpTech** [orientechnologies/orientdb#5091]
OrientDb: 2.0.14

Orientjs
```sql
begin
LET t0 = UPDATE Node SET Points = 0
LET t1 = UPDATE Node SET Position = "admin"
return [$t0, $t1]
```

Result:
```sql
[ { classId: -2, value: null }, { classId: -2, value: null } ]
```

Expect somethink like this:
```[ number, number ]```

Result in 2.1.2 but in Studio
```sql
{
    "result": [
        {
            "@type": "d",
            "@version": 0,
            "value": [
                13,
                13
            ]
        }
    ],
    "notification": "Query executed  in 0.091 sec. Returned 1 record(s)"
}
```

BTW: It is very hard to take orientdb serious when such simple things doesn't works. In almost every release there is a regression. Orientdb should be focused on qualitity not in features. This is my perspective in 6 month orientdb.

**Comment by zifnab87** [comment]
@StarpTech  "BTW: It is very hard to take orientdb serious when such simple things doesn't works. In almost every release there is a regression. Orientdb should be focused on qualitity not in features. This is my perspective in 6 month orientdb." I feel the same way.. OrientDB is trying to do many things instead of doing half and right. Like my issue here: #5089 made me halt developing since some things are breaking because of that and also I cannot run my tests without them freezing randomly because of that #5033.. That's why I might be moving to TitanDB/TinkerPop/Cassandra soon..

**Comment by lvca** [comment]
@StarpTech what's your goal? Retrieving the updated RIDs or the number of updated records?

**Comment by lvca** [comment]
@zifnab87 sorry you already have an open issue that by the way I cannot reproduce it (please provide a test case if you really want quick help). Please don't comment any other issue not related to the problem with your complaints. Thanks.

**Comment by red-0ne** [comment]
Isn't it related to !3994? maybe 7b3011e hasn't been merged to OrientDB 2.0/2.1 ?

**Comment by StarpTech** [comment]
@lvca I want to retrieve the same result like in 2.0.X and in studio in other words the count of updated records. At the moment I have to fire two seperate querys.

**Comment by zifnab87** [comment]
[offtopic]@lvca it won't happen again I am sorry. I am just very frustrated especially with the closed issue that should be reproducible.[/offtopic]

**Comment by lvca** [comment]
@StarpTech which version of orientjs are you using?

**Comment by StarpTech** [comment]
@lvca 2.0.0

**Comment by lvca** [comment]
Could you please try 2.1?

**Comment by StarpTech** [comment]
Of course I will do it but the driver is in alpha status even if it works it is not acceptable for production.

**Comment by lvca** [comment]
2.1 is not in alpha, it has been released about 2 weeks ago:

https://www.npmjs.com/package/orientjs

**Comment by StarpTech** [comment]
The master branch is 2.0.0 and in the readme of tag 2.0.1 they say 

"status: alpha This is work in progress, alpha quality software. Please report any bugs you find so that we can improve the library for everyone."

**Comment by StarpTech** [comment]
@lvca same result

```
[ { classId: -2, value: null }, { classId: -2, value: null } ]
```

**Comment by smolinari** [comment]
Reading this thread, if the correct result comes from Studio, then I'd deduce the problem is more likely in Orientjs, as Luca pointed out to try the newest version, I'd agree Orientjs is the place to look for the issue. There was a similar issue with the PHP driver cutting off longs to only 2 decimal places. It was reported in the PHPOrient repo and fixed relatively quickly. This issue might be better off in the Orientjs repo???

Scott

**Comment by StarpTech** [comment]
@smolinari if you read my last comment you can see that the issue on db level.

**Comment by smolinari** [comment]
How can Studio return the proper result, if the database is causing the issue? Or is it a different protocol being used for OrientJS than what Studio uses? 

Scott

**Comment by StarpTech** [comment]
Of course the binary protocol and http are different.

**Comment by lvca** [comment]
@StarpTech In order to understand where is the problem, could you try the sam batch from console, please?

**Comment by StarpTech** [comment]
Orientdb 2.1.4

Result via console

@lvca with a clean database and only 1 class called ``Node`
```
orientdb {db=test}> script sql
[Started multi-line command. Type just 'end' to finish and execute]
orientdb {db=test}> begin
orientdb {db=test}> LET t0 = UPDATE Node SET Points = 0
orientdb {db=test}> LET t1 = UPDATE Node SET Position = "admin"
orientdb {db=test}> return [$t0, $t1]
orientdb {db=test}> end

Server side script executed in 0.009000 sec(s). Value returned is: [0, 0]
```

with my develop database:

```
orientdb> script sql
[Started multi-line command. Type just 'end' to finish and execute]
orientdb> begin
orientdb> LET t0 = UPDATE Node SET Points = 0
orientdb> LET t1 = UPDATE Node SET Position = "admin"
orientdb> return [$t0, $t1]
orientdb> end

Error: java.lang.NullPointerException

orientdb>
```

**Comment by StarpTech** [comment]
@lvca anything new?

**Comment by StarpTech** [comment]
@lvca do you working on this?

**Comment by StarpTech** [comment]
@lvca any updates?

**Comment by obi1kenobi** [comment]
I hit what is likely the same issue via gremlin queries -- see the first example from the gremlin docs on the select operator:
http://gremlindocs.spmallette.documentup.com/#select
```
gremlin> g.v(1).as('x').out('knows').as('y').select
```

Via Studio, everything works fine. However, via the binary interface (using via `pyorient`), there are two cases. When `x` knows exactly one person, I get everything back correctly; however, when `x` knows more than one person, I get null records back, and OrientDB prints the following warning to the log:
```
WARNI {db=<...>} Cannot serialize record: [<...>] [ONetworkProtocolBinary]
```

**Comment by lvca** [comment]
Hi guys, we just released v2.1.6. Are you able to reproduce it with v2.1.6?

**Comment by obi1kenobi** [comment]
I'll attempt to repro as soon as `brew` is updated to show 2.1.6 as the newest version, hopefully in the next day or so.

**Comment by obi1kenobi** [comment]
Seems to work fine both in Studio and via the console in 2.1.6:
```
orientdb {db=multi_vertex}> gremlin g.v('#12:0').as('x').out('Knows').as('y').select
orientdb {db=multi_vertex}> end

[Person#12:0{name:abc,out_Knows:[size=1]} v2, Person#12:1{name:def,in_Knows:[size=1]} v2]
```

The issue should be closed. Thanks!

**Comment by lvca** [comment]
Cool, thanks.

**Comment by bodyclub24** [comment]
Its not fixed 

@lvca Tested with 2.1.8 in orientjs with:

```sql
begin
LET t0 = CREATE VERTEX Fitness CLUSTER DE_fitness content {"DisplayName":"Bernd Eck","Active":true,"Position":"fitness_member","Mid":"4561","Email":"berndeck1@local","Created":1451949088839}
LET t1 = UPDATE Node ADD References = $t0 WHERE Mid = "5681ee64b5c1433c28131e6e"
LET t2 = UPDATE $t0 SET SponsoredBy = ( select from Node WHERE Mid = "5681ee64b5c1433c28131e6e" )
commit\nreturn [$t0,$t1,$t2]
```

result: 

```
[ { '@type': 'd',
    '@class': 'Fitness',
    DisplayName: 'Bernd Eck',
    Active: true,
    Position: 'fitness_member',
    Mid: '4561',
    Email: 'berndeck1@local',
    Created: Tue Jan 05 2016 00:11:28 GMT+0100 (W. Europe Standard Time),
    SponsoredBy: { [String: '#18:0'] cluster: 18, position: 0 },
    '@rid': { [String: '#20:3'] cluster: 20, position: 3 },
    '@version': 1 },
  { classId: -2, value: null },
  { classId: -2, value: null } ]
```

**Comment by StarpTech** [comment]
Its not fixed 

@lvca Tested with 2.1.8 in orientjs with:

```sql
begin
LET t0 = CREATE VERTEX Fitness CLUSTER DE_fitness content {"DisplayName":"Bernd Eck","Active":true,"Position":"fitness_member","Mid":"4561","Email":"berndeck1@local","Created":1451949088839}
LET t1 = UPDATE Node ADD References = $t0 WHERE Mid = "5681ee64b5c1433c28131e6e"
LET t2 = UPDATE $t0 SET SponsoredBy = ( select from Node WHERE Mid = "5681ee64b5c1433c28131e6e" )
commit\nreturn [$t0,$t1,$t2]
```

result: 

```
[ { '@type': 'd',
    '@class': 'Fitness',
    DisplayName: 'Bernd Eck',
    Active: true,
    Position: 'fitness_member',
    Mid: '4561',
    Email: 'berndeck1@local',
    Created: Tue Jan 05 2016 00:11:28 GMT+0100 (W. Europe Standard Time),
    SponsoredBy: { [String: '#18:0'] cluster: 18, position: 0 },
    '@rid': { [String: '#20:3'] cluster: 20, position: 3 },
    '@version': 1 },
  { classId: -2, value: null },
  { classId: -2, value: null } ]
```

**Comment by obi1kenobi** [comment]
Can you check the server log and see if the same warning I was getting is printed there in your case? It might be a separate bug that is getting hit now.

**Comment by StarpTech** [comment]
@obi1kenobi the original issue was about orientjs and batch command. Your issue works with gremlin and console. I wondered why your issue was handled as the same. Your bug might be a seperate one. Thanks.

**Comment by obi1kenobi** [comment]
I figured that since we were both getting the same error (`Cannot serialize record: [<...>] [ONetworkProtocolBinary]`) in the log, it may be the same underlying issue. Sorry to hear it wasn't actually fixed, hope it gets fixed soon!

**Comment by StarpTech** [comment]
It still exists in 2.1.X please make a hotfix. This feature is essential to work with orientdb.

**Comment by StarpTech** [comment]
@luigidellaquila @lvca

**Comment by maggiolo00** [comment]
hi @StarpTech 

the problem is that the binary protocol is not able to to handle this result set

```
begin
LET t0 = CREATE VERTEX Fitness CLUSTER DE_fitness content {"DisplayName":"Bernd Eck","Active":true,"Position":"fitness_member","Mid":"4561","Email":"berndeck1@local","Created":1451949088839}
LET t1 = UPDATE Node ADD References = $t0 WHERE Mid = "5681ee64b5c1433c28131e6e"
LET t2 = UPDATE $t0 SET SponsoredBy = ( select from Node WHERE Mid = "5681ee64b5c1433c28131e6e" )
commit
return [$t0,$t1,$t2]
```

In your case would be

[Object,number,number]

You should wrap the return value in a single Object, something like this
```
begin
LET t0 = CREATE VERTEX Fitness CLUSTER DE_fitness content {"DisplayName":"Bernd Eck","Active":true,"Position":"fitness_member","Mid":"4561","Email":"berndeck1@local","Created":1451949088839}
LET t1 = UPDATE Node ADD References = $t0 WHERE Mid = "5681ee64b5c1433c28131e6e"
LET t2 = UPDATE $t0 SET SponsoredBy = ( select from Node WHERE Mid = "5681ee64b5c1433c28131e6e" )
commit
return  { "vertexCreated" : $t0, "nodeUpdated" : $t1, "fitnessUpdated" : $t2}
```

**Comment by StarpTech** [comment]
@maggiolo00 good to know. Is this safe for the future? Will it be fixed?

**Comment by nagarajasr** [comment]
doesn't work in 2.2.0-SNAPSHOT develop@r76eb89664869753ee518b741fd2009d2255877c8; 2016-03-14 03:29:50+0000:

```
orientdb {db=testdb}> script sql
[Started multi-line command. Type just 'end' to finish and execute]
orientdb {db=testdb}> begin
orientdb {db=testdb}> let t0 = update C1 set points = 0
orientdb {db=testdb}> let t1 = update C1 set position = "admin"
orientdb {db=testdb}> return { "first": $t0, "second": $t1 }
orientdb {db=testdb}> end

Server side script executed in 0.052000 sec(s). Value returned is: [null, null]

```

server log says:
```
2016-04-05 20:02:41:802 WARNI {db=testdb} Cannot serialize record: 1 [ONetworkProtocolBinary]
2016-04-05 20:02:41:804 WARNI {db=testdb} Cannot serialize record: 1 [ONetworkProtocolBinary]
```

**Comment by StarpTech** [comment]
@nagarajasr thanks for testing.

**Comment by maggiolo00** [comment]
@StarpTech 
@nagarajasr 

sorry yes you are right my bad. 
@tglman any hint on a fix on this?

**Comment by maggiolo00** [comment]
@StarpTech 

i've found a solution

You can write your batch in this way

```
begin
LET t0 = CREATE VERTEX Fitness CLUSTER DE_fitness content {"DisplayName":"Bernd Eck","Active":true,"Position":"fitness_member","Mid":"4561","Email":"berndeck1@local","Created":1451949088839}
LET t1 = UPDATE Node ADD References = $t0 WHERE Mid = "5681ee64b5c1433c28131e6e"
LET t2 = UPDATE $t0 SET SponsoredBy = ( select from Node WHERE Mid = "5681ee64b5c1433c28131e6e" )
commit
select $t0,$t1,$t2
```

**Comment by StarpTech** [comment]
@maggiolo00  Found or just checked out? Is this the common way? I build my base on such solutions.

**Comment by maggiolo00** [comment]
@StarpTech 

This will work because it is handle with the SQL of OrientDB so the result set.
The other one with custom return was never supported and will give error until the binary protocol will support this kind of serialization. The binary protocol is able to serialize only a collection of documents as result set. That is why you get because the collection returned from the batchScript is [Object,number,number]
```
2016-04-05 20:02:41:802 WARNI {db=testdb} Cannot serialize record: 1 [ONetworkProtocolBinary]
2016-04-05 20:02:41:804 WARNI {db=testdb} Cannot serialize record: 1 [ONetworkProtocolBinary]
```

**Comment by StarpTech** [comment]
Than the docu is completly wrong

```
return , where value can be:
any value. Example: return 3
any variable with $ as prefix. Example: return $a
arrays. Example: return [ $a, $b ]
maps. Example: return { 'first' : $a, 'second' : $b }
```

http://orientdb.com/docs/2.1/SQL-batch.html

**Comment by luigidellaquila** [comment]
That's bad.
As a first step I'm fixing the docs adding some clarifications.
Then we have to see how to fix these problems on the binary protocol (on http everything works fine, so the problem is in the serialization)

Thanks

Luigi

**Comment by StarpTech** [comment]
@maggiolo00 using the `select` statement fix it but now we are working with a different data structure. This example shows that the transaction feature must be refactored!
 e.g 

```
[ { '@type': 'd',
    '$t0': [ [Object] ],
    '$t1': { [String: '#17:0'] cluster: 17, position: 0 },
    '$t2': [ [Object] ],
    '$t3': 1,
    '$t4': 1,
    '@rid': { [String: '#-2:1'] cluster: -2, position: 1 },
    '@version': 0 } ]
```

**Comment by StarpTech** [comment]
@luigidellaquila seriously, we are talking about the result of an update statement. I'm ready to try develop releases but this issue exists since 4 months. Now, you are talking about a structural problem and that orientjs cant serialize simple literals. This is ok you can serve documents like SUM() it does but then in the correct response format (return { a: $b } or [$a]). Its hard for me to take orientdb seriously and I'm thinking about to change when such important issue dont fixed within a fair range.

**Comment by StarpTech** [comment]
@luigidellaquila is the http protocol more stable than the binary ?

**Comment by luigidellaquila** [comment]
Hi @StarpTech 

Probably it's not a matter of stability, just that the binary format does not support some kinds of result sets while the HTTP protocol.

In terms of stability I can say that they are equivalent.

Thanks

Luigi

**Comment by smolinari** [comment]
It would be nice to have the difference documented, so users can make an informed choice. That or get feature parity between the two protocols (which is what I would personally want). 

And what about performance? I would assume the binary protocol is faster?

Scott

**Comment by luigidellaquila** [comment]
@smolinari I added a note to the docs (not yet published, we will do it in short).

The HTTP protocol is a little bit slower than the binary one, because of the size of the messages, but the different is not significant compared to the whole elaboration

Thanks

Luigi

**Comment by StarpTech** [comment]
@luigidellaquila ok you prefer to use the http protocol when performance does not matter? Is the http protocol 100% compatible when I switch in orientjs to http ?

**Comment by maggiolo00** [comment]
hi @StarpTech 

orientjs api  should be te same with binary/rest but i cannot guarantee that it is 100% compatible. In a normal scenario you use http or binary. If you switch you will probably encounter some issues. We can with the help of @tglman try to solve this issue of the return of a batch script

**Comment by StarpTech** [comment]
The second solution would be the best. I think it can't be difficult to fix this in the binary driver. Please let me know when @tglman work on this issue.

**Comment by StarpTech** [comment]
@maggiolo00 What is the status of this issue? Is orientdb able to handle his own result sets ?
As very similiar issue I get in this example:


```sql
begin
		LET t0 = SELECT COUNT(*) FROM (TRAVERSE References FROM (SELECT FROM CLUSTER:[DE_business,Node, DE_root] WHERE Mid = '${userId}' ) MAXDEPTH 1 )
		LET t1 = SELECT FROM CLUSTER:[DE_business,Node, DE_root]
		return [$t0,$t1]
		commit
```

result:

```
{ data: { classId: -2, value: null }, count: 6 }
```

in studio it works.

**Comment by lvca** [comment]
Hey guys, what's the status of this issue?

**Comment by maggiolo00** [comment]
Hi @lvca 

I think it is done and should be released with OrientDB 2.1.17. 
@tglman  am i right?
It is done also in OrientJS as well but not yet released on npm

**Comment by StarpTech** [comment]
@maggiolo00 i'm afraid not!

Sorry @tglman @luigidellaquila @lvca  but I can't believe it. I kept trying in vain since two months and now I can determine a big issue or in other word mistake in the implementation of return literals in the binary driver.


OrientJs 2.1.11

```
begin
LET t0 = SELECT SUM(OrderPoints, UniPoints) as bodypoints FROM (TRAVERSE SponsoredBy FROM (SELECT FROM CLUSTER:[DE_business,Node, DE_root] WHERE Email = 'test@local')) WHERE $depth = 1
LET t1 = SELECT SUM(OrderPoints, UniPoints) as bodypoints FROM (TRAVERSE SponsoredBy FROM (SELECT FROM CLUSTER:[DE_business,Node, DE_root] WHERE Email = 'test@local')) WHERE $depth = 2
LET t2 = SELECT SUM(OrderPoints, UniPoints) as bodypoints FROM (TRAVERSE SponsoredBy FROM (SELECT FROM CLUSTER:[DE_business,Node, DE_root] WHERE Email = 'test@local')) WHERE $depth = 3
LET t3 = SELECT SUM(OrderPoints, UniPoints) as bodypoints FROM (TRAVERSE SponsoredBy FROM (SELECT FROM CLUSTER:[DE_business,Node, DE_root] WHERE Email = 'test@local')) WHERE $depth = 4
LET t4 = SELECT SUM(OrderPoints, UniPoints) as bodypoints FROM (TRAVERSE SponsoredBy FROM (SELECT FROM CLUSTER:[DE_business,Node, DE_root] WHERE Email = 'test@local')) WHERE $depth = 5
LET t5 = SELECT SUM(OrderPoints, UniPoints) as bodypoints FROM (TRAVERSE SponsoredBy FROM (SELECT FROM CLUSTER:[DE_business,Node, DE_root] WHERE Email = 'test@local')) WHERE $depth = 6
LET t6 = SELECT SUM(OrderPoints, UniPoints) as bodypoints FROM (TRAVERSE SponsoredBy FROM (SELECT FROM CLUSTER:[DE_business,Node, DE_root] WHERE Email = 'test@local')) WHERE $depth = 7
commit retry 100
return [$t0,$t1,$t2,$t3,$t4,$t5,$t6]

```

Result:
```
[ '[[],[],[],[],[],[],[]]' ]
```


Related:
http://www.prjhub.com/#/issues/5723

https://github.com/orientechnologies/orientdb/issues/5091

**Comment by maggiolo00** [comment]
@StarpTech 

what do you get if you execute this on studio?

```
begin
LET t0 = SELECT SUM(OrderPoints, UniPoints) as bodypoints FROM (TRAVERSE SponsoredBy FROM (SELECT FROM CLUSTER:[DE_business,Node, DE_root] WHERE Email = 'test@local')) WHERE $depth = 1
LET t1 = SELECT SUM(OrderPoints, UniPoints) as bodypoints FROM (TRAVERSE SponsoredBy FROM (SELECT FROM CLUSTER:[DE_business,Node, DE_root] WHERE Email = 'test@local')) WHERE $depth = 2
LET t2 = SELECT SUM(OrderPoints, UniPoints) as bodypoints FROM (TRAVERSE SponsoredBy FROM (SELECT FROM CLUSTER:[DE_business,Node, DE_root] WHERE Email = 'test@local')) WHERE $depth = 3
LET t3 = SELECT SUM(OrderPoints, UniPoints) as bodypoints FROM (TRAVERSE SponsoredBy FROM (SELECT FROM CLUSTER:[DE_business,Node, DE_root] WHERE Email = 'test@local')) WHERE $depth = 4
LET t4 = SELECT SUM(OrderPoints, UniPoints) as bodypoints FROM (TRAVERSE SponsoredBy FROM (SELECT FROM CLUSTER:[DE_business,Node, DE_root] WHERE Email = 'test@local')) WHERE $depth = 5
LET t5 = SELECT SUM(OrderPoints, UniPoints) as bodypoints FROM (TRAVERSE SponsoredBy FROM (SELECT FROM CLUSTER:[DE_business,Node, DE_root] WHERE Email = 'test@local')) WHERE $depth = 6
LET t6 = SELECT SUM(OrderPoints, UniPoints) as bodypoints FROM (TRAVERSE SponsoredBy FROM (SELECT FROM CLUSTER:[DE_business,Node, DE_root] WHERE Email = 'test@local')) WHERE $depth = 7
commit retry 100
return [$t0,$t1,$t2,$t3,$t4,$t5,$t6]
```

**Comment by StarpTech** [comment]
@maggiolo00 In Studio I get the correct result set.

**Comment by maggiolo00** [comment]
Can you post it here?

**Comment by StarpTech** [comment]
```
{
    "result": [
        {
            "@type": "d",
            "@version": 0,
            "value": [
                [
                    
                ],
                [
                    
                ],
                [
                    
                ],
                [
                    
                ],
                [
                    
                ],
                [
                    
                ],
                [
                    
                ]
            ]
        }
    ],
    "notification": "Query executed  in 0.064 sec. Returned 1 record(s)"
}
```

**Comment by maggiolo00** [comment]
@StarpTech 

those are empy array. If you try orientjs 2.1.17-beta you should see those well deserialized as i wrote you in prjhub

**Comment by maggiolo00** [comment]
if you confirm this i can promote the fix and release 2.1.17

**Comment by StarpTech** [comment]
@maggiolo00 good news it works like expected.

**Comment by StarpTech** [comment]
I couldn't know that a new version was released. You did it 2 hours ago ^^

**Comment by lvca** [comment]
Cool, so it looks like this is closed, right? Closing.
