### ISSUE TITLE
Database broken please help! - Binary protocol, serialization issue

### ISSUE THREAD

**Issue by StarpTech** [orientechnologies/orientdb#5226]
2,0.14 and 2.1.14

OrientJs Binary driver

@lvca  @maggiolo00 @luigidellaquila thanks for any tip!

The only solution is to import the latest backup. After a while it happens again with different nodes.

```
2015-10-26 19:20:08:200 WARNI {db=body_prod} Error deserializing record with id #18:3849 send this data for debugging: <base64 sensitive data block>  [ORecordSerializerBinary]{db=body_prod} Error on iterating record collection
com.orientechnologies.orient.core.exception.ODatabaseException: Error on retrieving record #18:3849 (cluster: de_business)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1780)
	at com.orientechnologies.orient.core.tx.OTransactionNoTx.loadRecord(OTransactionNoTx.java:100)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:1550)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.load(ODatabaseDocumentTx.java:120)
	at com.orientechnologies.orient.core.id.ORecordId.getRecord(ORecordId.java:324)
	at com.orientechnologies.orient.core.db.record.OLazyRecordIterator.next(OLazyRecordIterator.java:75)
	at com.orientechnologies.orient.core.db.record.OLazyRecordIterator.next(OLazyRecordIterator.java:38)
	at com.orientechnologies.orient.core.type.tree.OMVRBTreeRID.putAll(OMVRBTreeRID.java:171)
	at com.orientechnologies.orient.core.type.tree.OMVRBTreeRID.<init>(OMVRBTreeRID.java:61)
	at com.orientechnologies.orient.core.type.tree.OMVRBTreeRIDSet.<init>(OMVRBTreeRIDSet.java:77)
	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerCSVAbstract.fieldToStream(ORecordSerializerCSVAbstract.java:452)
	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerSchemaAware2CSV.toString(ORecordSerializerSchemaAware2CSV.java:506)
	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerStringAbstract.toStream(ORecordSerializerStringAbstract.java:689)
	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerSchemaAware2CSV.toStream(ORecordSerializerSchemaAware2CSV.java:268)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:2282)
	at com.orientechnologies.orient.core.record.impl.ODocument.toStream(ODocument.java:671)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.getRecordBytes(OBinaryNetworkProtocolAbstract.java:424)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.writeRecord(OBinaryNetworkProtocolAbstract.java:443)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.writeIdentifiable(OBinaryNetworkProtocolAbstract.java:141)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.serializeValue(ONetworkProtocolBinary.java:1389)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1337)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:396)
	at com.orientechnologies.orient.server.network.protocol.binary.OBinaryNetworkProtocolAbstract.execute(OBinaryNetworkProtocolAbstract.java:223)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
Caused by: com.orientechnologies.orient.core.exception.OSerializationException: Error on unmarshalling field 'Email' in record #18:3849 with value: Email:"aernrhard@memo.com"
	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerSchemaAware2CSV.fromString(ORecordSerializerSchemaAware2CSV.java:258)
	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerStringAbstract.fromStream(ORecordSerializerStringAbstract.java:677)
	at com.orientechnologies.orient.core.record.ORecordAbstract.fromStream(ORecordAbstract.java:129)
	at com.orientechnologies.orient.core.record.impl.ODocument.fromStream(ODocument.java:1442)
	at com.orientechnologies.orient.core.record.impl.ODocument.fromStream(ODocument.java:81)
	at com.orientechnologies.orient.core.db.document.ODatabaseDocumentTx.executeReadRecord(ODatabaseDocumentTx.java:1765)
	... 23 more
Caused by: java.lang.ArrayIndexOutOfBoundsException: 78
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.fromStream(ORecordSerializerBinary.java:72)
	at com.orientechnologies.orient.core.record.impl.ODocument.deserializeFields(ODocument.java:1817)
	at com.orientechnologies.orient.core.record.impl.ODocument.checkForFields(ODocument.java:2405)
	at com.orientechnologies.orient.core.record.impl.ODocument.containsField(ODocument.java:1328)
	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerSchemaAware2CSV.fromString(ORecordSerializerSchemaAware2CSV.java:154)
	... 28 more
```

base 64 node
```
Node@Email:"agerhard@memo.com",Mid:"561f92f30f468ba750819",Position:"partner",DisplayName:"Gerhard Aerni",Active:true,Created:1444910030850t,SponsoredBy:#18:2062,OrderPoints:0.0d,UniPoints:0.0d,BinPoints:0.0d,Points:0,in_BroughtIntoRight:%AQAAAAEAFwAAAAAAAAe4AAAAAAAAAAAAAA==;,InsertedAtDepth:21,out_BroughtIntoRight:%AQAAAAEAFwAAAAAAAAfEAAAAAAAAAAAAAA==;,Node/
1!5:"-©ЫьPointsׁ&in_BroughtIntoRightؖ9ញnsertedAtDepth䁨out_BroughtIntoRight喇EC&aernigerhard@me.com0561f92f30f468b5f7a750819partnertom Aerni˵
T8$ *Ā"         
```

**Comment by maggiolo00** [comment]
@tglman any tips?

**Comment by tglman** [comment]
it looks like there is something wrong happening with the choice of the correct serializer, i'll check that

**Comment by StarpTech** [comment]
@maggiolo00 @tglman  thanks for the fast response

**Comment by tglman** [comment]
Reading the stack trace i saw that is doing some lazy load while serializing, that should  not happen, i fixed it, it will be out with the next hotfix.

@StarpTech Do you have the chance to check this in environment ?

**Comment by StarpTech** [comment]
yes I have. Where can I get the hotfix ASAP? Do you make an 2.1.4 release?

**Comment by StarpTech** [comment]
but I will try to reproduce the issue when the hotfix is released.

**Comment by StarpTech** [comment]
@tglman how can i get this fix?

**Comment by StarpTech** [comment]
@tglman I have build from 2.1.X branch but the error still occurs

```
java.lang.ArrayIndexOutOfBoundsException: 78
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.fromStream(ORecordSerializerBinary.java:74)
	at com.orientechnologies.orient.core.record.impl.ODocument.deserializeFields(ODocument.java:1817)
	at com.orientechnologies.orient.core.record.impl.ODocument.checkForFields(ODocument.java:2405)
	at com.orientechnologies.orient.core.record.impl.ODocument.fieldNames(ODocument.java:736)
	at com.orientechnologies.orient.core.fetch.OFetchHelper.processRecord(OFetchHelper.java:291)
	at com.orientechnologies.orient.core.fetch.OFetchHelper.fetch(OFetchHelper.java:82)
	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerJSON.toString(ORecordSerializerJSON.java:335)
	at com.orientechnologies.orient.core.serialization.serializer.record.string.ORecordSerializerStringAbstract.toString(ORecordSerializerStringAbstract.java:666)
	at com.orientechnologies.orient.core.record.ORecordAbstract.toJSON(ORecordAbstract.java:192)
	at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse.formatMultiValue(OHttpResponse.java:380)
	at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse.writeRecords(OHttpResponse.java:330)
	at com.orientechnologies.orient.server.network.protocol.http.OHttpResponse.writeResult(OHttpResponse.java:226)
	at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:103)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:180)
	at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:627)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)

```

**Comment by StarpTech** [comment]
Could it be error cause the broken node ?

**Comment by StarpTech** [comment]
@tglman the exception above is thrown almost on any commands. In studio the commands works as expected. It still a serialization problem.

**Comment by tglman** [comment]
@StarpTech the last stack trace is over http, but yes the main cause is the orientjs and the java using two different serializations.

I think this errors are a symptom of an error happened before, are you able to identify what are the record in error and what is the functionality that created or updated them ?

It's probably a command script or an update operation that has the mistake, but it's hard  to identify it without a direct error or reproducible test case.

**Comment by StarpTech** [comment]
@tglman I do nothing with http. I tested your hotfix against the latest SNAPSHOT 2.1.5. In my logs I cant see any errors expect lots of messages like "'#18:1105' not found in traverse history [OTraverseContext]" I think we've done it! Thank you very much for the fast response and for the help. If the problems comes back I will try to post a test case with sample data.

**Comment by lvca** [comment]
Cool, closing it.

**Comment by kxc1573** [comment]
Hi @tglman and @lvca , I came across this problem again recently when I use OrientDB 3.1.15 on RHEL 8 -- zlinux.
Here the last part log of OrientDB

> $ANSI{green {db=Demo}} Error while binary response serialization
com.orientechnologies.orient.core.exception.OSerializationException: Error on unmarshalling record #53:285 (java.lang.NegativeArraySizeException: -2057971028)
	DB name="Demo"
	at com.orientechnologies.orient.client.remote.message.OMessageHelper.writeRecord(OMessageHelper.java:76)
	at com.orientechnologies.orient.client.remote.message.OMessageHelper.writeIdentifiable(OMessageHelper.java:57)
	at com.orientechnologies.orient.client.remote.message.OMessageHelper.writeDocument(OMessageHelper.java:459)
	at com.orientechnologies.orient.client.remote.message.OMessageHelper.writeVertex(OMessageHelper.java:440)
	at com.orientechnologies.orient.client.remote.message.OMessageHelper.writeResult(OMessageHelper.java:468)
	at com.orientechnologies.orient.client.remote.message.OQueryResponse.write(OQueryResponse.java:68)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:391)
	at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:239)
	at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:67)
Caused by: java.lang.NegativeArraySizeException: -2057971028
	at java.base/java.util.Base64$Encoder.encode(Base64.java:268)
	at java.base/java.util.Base64$Encoder.encodeToString(Base64.java:321)
	at com.orientechnologies.orient.core.serialization.serializer.record.binary.ORecordSerializerBinary.fromStream(ORecordSerializerBinary.java:111)
	at com.orientechnologies.orient.core.record.impl.ODocument.deserializeFields(ODocument.java:2428)
	at com.orientechnologies.orient.client.remote.message.OMessageHelper.getRecordBytes(OMessageHelper.java:89)
	at com.orientechnologies.orient.client.remote.message.OMessageHelper.writeRecord(OMessageHelper.java:69)	... 8 more

I guess this is also caused by that the orientjs and the java using two different serializations.
What's your opinion?


I want to briefly describe my workflow, which is to transfer data from postgrsql to orientdb

First create many new vertices, and then add many edges

But in the process of adding edges, I sometimes add attributes to some vertices Then, in the process, they reported an error


What is strange is that if I remove the operation of updating vertices during the process of creating new edges, and only create all vertices and then all edges, the whole process will be completed smoothly.
