### ISSUE TITLE
studio vertex detail form doesn't load

### ISSUE THREAD

**Issue by bazo** [orientechnologies/orientdb#5248]
hi,

when i want to view properties of certain vertex classes, the form is not loaded
in firebug i can see a bunch of ajax requests

````
http://localhost:2480/sqlProfiler/dbname
````

this one says method not allowed, response is
````
{
  "errors": [{
      "code": 405,
      "reason": 405,
      "content": "Command not found: sqlProfiler/sutaz"
      }
  ]
}
````

then this one
````
http://localhost:2480/studio/views/widget/form.html
````
it's ok but immediately after completing an error is thrown

````
Error: invalid array length
compileForm/</<@http://localhost:2480/studio/scripts/scripts.js:41634:40
compileForm/<@http://localhost:2480/studio/scripts/scripts.js:41633:9
Yd/this.$get</k.prototype.$digest@http://localhost:2480/studio/scripts/scripts.js:114:373
Yd/this.$get</k.prototype.$apply@http://localhost:2480/studio/scripts/scripts.js:117:360
h@http://localhost:2480/studio/scripts/scripts.js:77:325
x@http://localhost:2480/studio/scripts/scripts.js:82:288
we/</z.onreadystatechange@http://localhost:2480/studio/scripts/scripts.js:83:340
````

this happens on class level but only for some classes

orientdb 2.1.5 community, and also 2.1.4

**Comment by maggiolo00** [comment]
Hi @bazo 
i'm not able to reproduce it with OrientDB 2.2.2. Can you confirm that it is fixed?

**Comment by maggiolo00** [comment]
@bazo 

any news on this?

**Comment by maggiolo00** [comment]
hi @bazo 

i'will  label this as `Cannot replicate` since i'm not able to reproduce it.
If you are still experimenting this issue with ODB 2.2.x, please reopen it.

Thanks

**Comment by bazo** [comment]
hi,

i got around to continue with the project i encountered this bug with and it still persists. i could send you the database or some data to debug this if you want

**Comment by RolT** [comment]
I also encountered this issue for verticles that have a property called "length" (with orientdb 2.2.37).

**Comment by tglman** [comment]
@RolT 

I definitely suggest to update to the last 3.2.x the 2.2.x is out of support for a few years now.
