### ISSUE TITLE
Type ANY does not support converting value:

### ISSUE THREAD

**Issue by iamlogiq** [orientechnologies/orientdb#6184]
## Expected behavior and actual behaviour

I cannot create a model who has a property type of ANY. 

## Steps to reproduce the problem

I have a model (A) with a property of type ANY. I have another model (B) with a property that is an embeddedList of model (A). When I create model B's property i get an error everytime the type of the value is a string, bool, integer ect. I only works if the property of the type ANY is an array or object. 

## Important Questions

My question is how can i store a string, bool, date, integer ect in a property who's type is ANY?

### Runninng Mode
- [X ] Embedded, using PLOCAL access mode

### OrientDB Version
- [ x] v2.2.x - Please specify last number: 0

### Operating System
- [ x] MacOSX

### Java Version
- [ ] 6
- [ ] 7
- [ ] 8

**Comment by lvca** [comment]
I think this is related to https://github.com/orientechnologies/orientdb/issues/6153 that it's already resolved in develop branch. Could you try it please?

**Comment by iamlogiq** [comment]
@lvca I can't seem to install the develop branch. It keeps failing when when run mvn clean install

[INFO] OrientDB ........................................... SUCCESS [  0.972 s]
[INFO] OrientDB Test Commons .............................. SUCCESS [  0.998 s]
[INFO] OrientDB Core ...................................... FAILURE [01:27 min]
[INFO] OrientDB Client .................................... SKIPPED
[INFO] OrientDB Object .................................... SKIPPED
[INFO] OrientDB Tools ..................................... SKIPPED
[INFO] OrientDB Server .................................... SKIPPED
[INFO] OrientDB GraphDB ................................... SKIPPED
[INFO] OrientDB Tests ..................................... SKIPPED
[INFO] OrientDB Distributed Server ........................ SKIPPED
[INFO] OrientDB Lucene full text index .................... SKIPPED
[INFO] OrientDB JDBC Driver ............................... SKIPPED
[INFO] OrientDB ETL ....................................... SKIPPED
[INFO] OrientDB Community Distribution .................... SKIPPED

**Comment by lvca** [comment]
Just executed:

```
[INFO] Reactor Summary:
[INFO]
[INFO] OrientDB ........................................... SUCCESS [  0.655 s]
[INFO] OrientDB Test Commons .............................. SUCCESS [  0.928 s]
[INFO] OrientDB Core ...................................... SUCCESS [01:34 min]
[INFO] OrientDB Client .................................... SUCCESS [  3.109 s]
[INFO] OrientDB Object .................................... SUCCESS [  6.698 s]
[INFO] OrientDB Tools ..................................... SUCCESS [  3.915 s]
[INFO] OrientDB Server .................................... SUCCESS [ 22.840 s]
[INFO] OrientDB GraphDB ................................... SUCCESS [ 36.652 s]
[INFO] OrientDB Tests ..................................... SUCCESS [02:39 min]
[INFO] OrientDB Distributed Server ........................ SUCCESS [  2.975 s]
[INFO] OrientDB Lucene full text index .................... SUCCESS [ 21.414 s]
[INFO] OrientDB JDBC Driver ............................... SUCCESS [01:09 min]
[INFO] OrientDB ETL ....................................... SUCCESS [ 25.192 s]
[INFO] OrientDB Community Distribution .................... SUCCESS [  0.038 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 07:27 min
[INFO] Finished at: 2016-05-23T16:11:31+02:00
[INFO] Final Memory: 174M/954M
```

Could you retry? Maybe you've got a push in the middle?

**Comment by iamlogiq** [comment]
@lvca 
Hi, it's still not working. what did you mean by push in the middle?
`
Failed tests:
  ODocumentSchemalessBinarySerializationTest.testSimpleSerialization:143 expected [Mon May 23 00:00:00 EDT 2016] but found [Mon May 23 12:00:00 EDT 2016]
  ODocumentSerializerNetworkTest>ODocumentSchemalessBinarySerializationTest.testSimpleSerialization:143 expected [Mon May 23 00:00:00 EDT 2016] but found [Mon May 23 12:00:00 EDT 2016]
  OCommandExecutorSQLSelectTest.testDatesListContainsString:990 expected [1] but found [0]

Tests run: 1407, Failures: 3, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] OrientDB ........................................... SUCCESS [  1.096 s]
[INFO] OrientDB Test Commons .............................. SUCCESS [  1.060 s]
[INFO] OrientDB Core ...................................... FAILURE [01:28 min]
[INFO] OrientDB Client .................................... SKIPPED
[INFO] OrientDB Object .................................... SKIPPED
[INFO] OrientDB Tools ..................................... SKIPPED
[INFO] OrientDB Server .................................... SKIPPED
[INFO] OrientDB GraphDB ................................... SKIPPED
[INFO] OrientDB Tests ..................................... SKIPPED
[INFO] OrientDB Distributed Server ........................ SKIPPED
[INFO] OrientDB Lucene full text index .................... SKIPPED
[INFO] OrientDB JDBC Driver ............................... SKIPPED
[INFO] OrientDB ETL ....................................... SKIPPED
[INFO] OrientDB Community Distribution .................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:30 min
[INFO] Finished at: 2016-05-23T14:35:04-04:00
[INFO] Final Memory: 48M/703M
`

**Comment by lvca** [comment]
What's your JVM and OS?

**Comment by tglman** [comment]
hi @iamlogiq,

I think this is an issue with date type and timezones, from the failure it seems nothing too wrong is going on, probably is not correct the assert that check also the time and not just the date.

bye

**Comment by iamlogiq** [comment]
@lvca @tglman 
Hi, im using a MAC running OSX El Capitan version 10.11 Beta (15A279b) my JVM version is
`
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)
`

**Comment by tglman** [comment]
hi @iamlogiq,

We fixed some issue recently on that, now should work without problem.

can you check again with 2.2.2

**Comment by iamlogiq** [comment]
Hi @tglman Is it fixed on the normal distribution on orientdb.com or only in the develop branch of this github repo?

**Comment by lvca** [comment]
Normal distribution 2.2.2 on the web site.

**Comment by iamlogiq** [comment]
Thanks!!

**Comment by tglman** [comment]
hi @iamlogiq,

Any news about this ? can we close this ?

**Comment by iamlogiq** [comment]
@tglman Yes. thanks!
