### ISSUE TITLE
Cannot create Index

### ISSUE THREAD

**Issue by ashwin1209** [orientechnologies/orientdb#6496]
We are trying to upgrade orientdb from 2.1.16 to 2.2.4 without changing the existing database.

steps followed
1. exported database from 2.1.16
2. imported into 2.2.4

giving following exception for one of the existing index.

com.orientechnologies.orient.core.index.OIndexException: Cannot create the index 'Object.objProp'
        DB name="wcods"
        DB name="wcods"
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:525)
        at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.throwSerializedException(OChannelBinaryAsynchClient.java:427)
        at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.handleStatus(OChannelBinaryAsynchClient.java:378)
        at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:260)
        at com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:152)
        at com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:2087)
        at com.orientechnologies.orient.client.remote.OStorageRemote$27.execute(OStorageRemote.java:1137)
        at com.orientechnologies.orient.client.remote.OStorageRemote$2.execute(OStorageRemote.java:192)
        at com.orientechnologies.orient.client.remote.OStorageRemote.baseNetworkOperation(OStorageRemote.java:224)
        at com.orientechnologies.orient.client.remote.OStorageRemote.networkOperation(OStorageRemote.java:189)
        at com.orientechnologies.orient.client.remote.OStorageRemote.command(OStorageRemote.java:1113)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:69)
        at com.orientechnologies.orient.core.index.OIndexManagerRemote.createIndex(OIndexManagerRemote.java:62)
        at com.orientechnologies.orient.core.index.OIndexManagerProxy.createIndex(OIndexManagerProxy.java:87)
        at com.orientechnologies.orient.core.db.tool.ODatabaseImport.importIndexes(ODatabaseImport.java:1483)
        at com.orientechnologies.orient.core.db.tool.ODatabaseImport.importDatabase(ODatabaseImport.java:418)
        at com.orientechnologies.orient.console.OConsoleDatabaseApp.importDatabase(OConsoleDatabaseApp.java:2125)
        at com.orientechnologies.orient.graph.console.OGremlinConsole.importDatabase(OGremlinConsole.java:136)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:601)
        at com.orientechnologies.common.console.OConsoleApplication.execute(OConsoleApplication.java:394)
        at com.orientechnologies.common.console.OConsoleApplication.executeCommands(OConsoleApplication.java:249)
        at com.orientechnologies.common.console.OConsoleApplication.run(OConsoleApplication.java:128)
        at com.orientechnologies.orient.graph.console.OGremlinConsole.main(OGremlinConsole.java:67)
Caused by: java.lang.NullPointerException
1. "objProp" is of type EMBEDDEDLIST with LINKCLASS as another entity "Property"

in 2.1.16 we were able to create this index as FULLTEXT with LUCENE engine.

but we are unable to create the same even from browser. Causing this exception

{"code":500,"reason":500,"content":"com.orientechnologies.orient.core.index.OIndexException: Cannot create the index 'Object.objProp'\r\n\tDB name=\"wcods\"\r\n--> java.lang.NullPointerException"}]}

**Comment by maggiolo00** [comment]
hi @ashwin1209  
can you try to import the database in plocal mode?


Btw database created with 2.1.x are binary compatible with 2.2.x you can avoid to export and import, just copy the db folder

http://orientdb.com/docs/2.2/Release-2.2.0.html#migration-from-21x-to-22x

**Comment by ashwin1209** [comment]
@maggiolo00  database is already created in plocal mode. For confirmation I re-created the database with plocal mode. But still the same exception occurs.

**Comment by maggiolo00** [comment]
@ashwin1209 

yes i meant with import use plocal connection instead of remote one

**Comment by ashwin1209** [comment]
@maggiolo00 : tried as suggested, but no luck :(

**Comment by maggiolo00** [comment]
@ashwin1209 
do you have the log exception of the Server?

Did you try to migrate with copying the directory?

**Comment by ashwin1209** [comment]
no, I am trying to import the database from 2.1.16 to 2.2.4

following is the server log respective to the exception.

java.lang.NullPointerException
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.addIndexEngine(OAbstractPaginatedStorage.java:1658)
        at com.orientechnologies.orient.core.index.OIndexAbstract.create(OIndexAbstract.java:235)
        at com.orientechnologies.lucene.index.OLuceneIndexNotUnique.create(OLuceneIndexNotUnique.java:197)
        at com.orientechnologies.lucene.index.OLuceneIndexNotUnique.create(OLuceneIndexNotUnique.java:45)
        at com.orientechnologies.orient.core.index.OIndexManagerShared.createIndex(OIndexManagerShared.java:177)
        at com.orientechnologies.orient.core.index.OIndexManagerProxy.createIndex(OIndexManagerProxy.java:87)
        at com.orientechnologies.orient.core.metadata.schema.OClassImpl.createIndex(OClassImpl.java:1857)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLCreateIndex.execute(OCommandExecutorSQLCreateIndex.java:277)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:72)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:2602)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:2548)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:69)
        at com.orientechnologies.orient.server.network.protocol.http.command.post.OServerCommandPostCommand.execute(OServerCommandPostCommand.java:107)
        at com.orientechnologies.orient.graph.server.command.OServerCommandPostCommandGraph.execute(OServerCommandPostCommandGraph.java:37)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.service(ONetworkProtocolHttpAbstract.java:165)
        at com.orientechnologies.orient.server.network.protocol.http.ONetworkProtocolHttpAbstract.execute(ONetworkProtocolHttpAbstract.java:613)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)

2016-08-02 16:40:51:539 SEVER Internal server error:
com.orientechnologies.orient.core.index.OIndexException: Cannot create the index 'Object.objProp'
        DB name="wcods"
--> java.lang.NullPointerException [ONetworkProtocolHttpDb]

**Comment by maggiolo00** [comment]
@ashwin1209 

do you have a sample export that i can use to test it?
you can send it to 
e.risa@orientdb.com if you want

**Comment by ashwin1209** [comment]
@maggiolo00 : we work in secure environment, it would be difficult forward any sample.

**Comment by maggiolo00** [comment]
@ashwin1209 

you should try the latest version 2.2.6 i think that problem was fixed. 
Can you try to import in 2.2.6?

**Comment by ashwin1209** [comment]
same exception in 2.2.6

**Comment by maggiolo00** [comment]
@ashwin1209 
if you create the index later?

**Comment by ashwin1209** [comment]
Do you mean to
1. import the database
2. create index after that.

tried these steps as well. Still no luck.

What I observed is that a property of type EMBEDDEDLIST and with "linkclass" assigned  giving exception if we are creating FULLTEXT index (LUCENE engine).

while  we alter the property  as type LINKLIST with "linkclass" not raising any exception.

we are able to create FULLTEXT index (LUCENE engine).

EMBEDDEDLIST-> stores complete values in column
LINKLIST-> stores only the references or link to the class

but we cannot alter this property as we have complex search queries defined on the  parent class containing value of this property

**Comment by ashwin1209** [comment]
any help on this issue?

**Comment by maggiolo00** [comment]
@ashwin1209 

i'm trying to reproduce it.
Can you help me on this?

**Comment by maggiolo00** [comment]
Do you have any script or something?

`Object.objProp` is Embedded of Strings?

**Comment by ashwin1209** [comment]
Object.objProp is EmbeddedList of another class "Property"

**Comment by maggiolo00** [comment]
@ashwin1209 

were you able to solve it?

**Comment by ashwin1209** [comment]
No luck with 2.2.4 version, but the same database I can export to 2.1.23 from 2.1.16.

**Comment by maggiolo00** [comment]
@ashwin1209 

with the latest 2.2.9?

**Comment by lvca** [comment]
I'm closing this issue because of no response since a while. In case the issue is still valid, please reopen/comment this. Thanks.
