### ISSUE TITLE
Reached maximum number of concurrent connections

### ISSUE THREAD

**Issue by ashwin1209** [orientechnologies/orientdb#6635]
Orientdb version-2.1.16
Java : Orientdb-client -2.1.16
1. Orient-db-server-config.xml : pool size configuration
   
   ```
   <entry name="server.database.path" value="${ORIENT_DB_DIR}/databases"/>
   <entry value="30" name="db.pool.min"/>
   <entry value="300" name="db.pool.max"/>
   <entry name="cache.local.enabled" value="true" />
   <entry value="true" name="profiler.enabled"/>
   <entry value="info" name="log.console.level"/>
   <entry value="fine" name="log.file.level"/>
   <entry name="distributed.crudTaskTimeout" value="15000"/>
   <entry name="distributed.queueTimeout" value="30000"/>
   <entry name="distributed.asynchResponsesTimeout" value="60000"/>
   <entry name="distributed.purgeResponsesTimerDelay" value="60000"/>
   <entry name="distributed.commandTaskTimeout" value="120000"/>
   ```
2.  java code connection configuration
   
   dbConntectionPoolA = new OPartitionedDatabasePool("remote:localhost/db", "xyz", "pwd", "10", "120")

and closing the connection in finally block.

Still we are facing this issue of "reached maximum number of connections".

because the number of  opened connections are 951

**Comment by tglman** [comment]
hi @ashwin1209,

What do you use client side ? it can happen that there is some proble on closing sessions client side.

Regard

**Comment by ashwin1209** [comment]
sample java client code.

ODatabaseDocumentTx connection=null;
try{
connection = new OPartitionedDatabasePool("remote:localhost/db", "xyz", "pwd", "10", "120").aquire();

ODocument oDoc= new Odocument();
oDoc.field("name","abc");

oDoc.save();
}catch (Exception exception) {
		LOGGER.error( exception);
	} 
	finally {
			connection.close();
		}

**Comment by tglman** [comment]
Hi @ashwin1209,

we had some issue on the OPartitionedDatabasePool that was not blocking, this as been fixed in a more recent hotfix that 2.1.16, can you please retry with the last hotfix (currentry 2.1.23) ? 

Bye

**Comment by ashwin1209** [comment]
Updated to 2.1.23, but one observation I found was.
1. Configured Orientdb server as mentioned above.
<entry name="server.database.path" value="${ORIENT_DB_DIR}/databases"/>
<entry value="30" name="db.pool.min"/>
<entry value="300" name="db.pool.max"/>
<entry name="cache.local.enabled" value="true" />
<entry value="true" name="profiler.enabled"/>
<entry value="info" name="log.console.level"/>
<entry value="fine" name="log.file.level"/>
<entry name="distributed.crudTaskTimeout" value="15000"/>
<entry name="distributed.queueTimeout" value="30000"/>
<entry name="distributed.asynchResponsesTimeout" value="60000"/>
<entry name="distributed.purgeResponsesTimerDelay" value="60000"/>
<entry name="distributed.commandTaskTimeout" value="120000"/>

2. I have 2 instance of my java application connecting to orientdb to read content.
client configuration are
connection = new OPartitionedDatabasePool("remote:localhost/db", "xyz", "pwd", "10", "120").aquire();

3. configured Jmeter to access 2 different instance of java applications, and hitting with 25 threads repeating for 20 times each

4. when I check the Orientdb binary connections around 30  are created and they remain in memory for ever until I completely close the java applications.

these connections are released into pool on calling db.close() and never gets closed. 

When I start a new java application instance with the remaining 2 instances still up, but not hitting the orientdb . A New set of connections are created instead of reading from existing pool of connections.

are there any issues with my configurations? or is it the normal behavior with OpartitionedDatabasePool?

**Comment by ashwin1209** [comment]
After updating database to 2.1.23, unable to access the db through java client ver 2.1.23?

**Comment by tglman** [comment]
hi @ashwin1209,

what do you mean that you are no able to access the database ?

anyway we fixed  a similar session issue on 2.2.10, consider to start schedule the migration to 2.2, the 2.1 will go out of support in the next few months.

bye

**Comment by G4br13l3** [comment]
Hi @ashwin1209,

did you try with 2.2.x?

Thanks.

**Comment by leosimoesp** [comment]
Hi, I've the same problem. 
I'm using orientdb 2.2.14 with scala. The connections aren't closed and application crashes.

 val poolFactory = new OPartitionedDatabasePoolFactory()
    poolFactory.setMaxPoolSize(40)

    val pool = poolFactory.get("remote:db.adimplere.com.br/adimplere", "admin", "sXcdsss098.")
    val conn = pool.acquire()

   try {
       val query = StringBuilder.newBuilder

      query.append("SELECT @this.tojson(\"fetchPlan:*:-1\") AS itens FROM Parceiro limit 1000;")

     val res = conn.query[java.util.List[ODocument]](new OSQLSynchQuery[ODocument](query.toString)).asScala.toList

      val result = {
        if (res.isEmpty) {
          None
        } else {
          Some(res(0).field("itens"))
        }
      }

      result

    } finally {
      conn.close()
      pool.close()
      poolFactory.close()
    }

  After execute, connection stay alive but pool was closed.

   netstat -ant | fgrep 2424
   tcp6       0      0 :::2424                 :::*                    LISTEN     
   tcp6       0      0 172.17.0.1:51928        172.17.0.1:2424         ESTABLISHED

**Comment by mmacfadden** [comment]
I seem to be having a similar issue.

```scala
val dbPool = new OPartitionedDatabasePool(uri, username, password, 1, 64)
```
I think have many threads that can request a connection using the acquire() method. The database is closed when the process is done. If I put the system under heavy load, I still get the following exception:
```
java.lang.IllegalStateException: You have reached maximum pool size for given partition
	at com.orientechnologies.orient.core.db.OPartitionedDatabasePool.acquire(OPartitionedDatabasePool.java:243)
```

I also tried the default parameters.

```scala
val dbPool = new OPartitionedDatabasePool(uri, username, password)
```

Same issue. It does not seem to be waiting for a connection. This is on 2.2.18 using the remote protocol.

**Comment by mmacfadden** [comment]
I actually think I may have been mistaken. I have two places I am using this code. I fixed one but not the other. This may be working properly now.  Verifying.

**Comment by tglman** [comment]
Hi,

2.1.x is not supported anymore and this issue is solved in more recent versions, closing

Regards
