### ISSUE TITLE
always problems with closing Lucene index during server shutdown

### ISSUE THREAD

**Issue by rdelangh** [orientechnologies/orientdb#6808]
## OrientDB Version, operating system, or hardware.
- v2.2.x (up till and including 2.2.12-20161019.051435-38)
## Operating System
- [x] Linux
## Expected behavior and actual behavior

During shutdown, I always notice that the logs have an error message about the closing of Lucene index : 

```
Error on closing Lucene index
java.nio.channels.ClosedByInterruptException
        at java.nio.channels.spi.AbstractInterruptibleChannel.end(AbstractInterruptibleChannel.java:202)
        at sun.nio.ch.FileChannelImpl.size(FileChannelImpl.java:315)
        at org.apache.lucene.store.NativeFSLockFactory$NativeFSLock.ensureValid(NativeFSLockFactory.java:170)
        at org.apache.lucene.store.LockValidatingDirectoryWrapper.createOutput(LockValidatingDirectoryWrapper.java:43)
        at org.apache.lucene.index.SegmentInfos.write(SegmentInfos.java:516)
        at org.apache.lucene.index.SegmentInfos.prepareCommit(SegmentInfos.java:809)
        at org.apache.lucene.index.IndexWriter.startCommit(IndexWriter.java:4439)
        at org.apache.lucene.index.IndexWriter.prepareCommitInternal(IndexWriter.java:2874)
        at org.apache.lucene.index.IndexWriter.commitInternal(IndexWriter.java:2977)
        at org.apache.lucene.index.IndexWriter.commit(IndexWriter.java:2944)
        at com.orientechnologies.lucene.engine.OLuceneIndexEngineAbstract.closeIndex(OLuceneIndexEngineAbstract.java:306)
        at com.orientechnologies.lucene.engine.OLuceneIndexEngineAbstract.close(OLuceneIndexEngineAbstract.java:341)
        at com.orientechnologies.lucene.engine.OLuceneIndexEngineAbstract.onShutdown(OLuceneIndexEngineAbstract.java:483)
        at com.orientechnologies.orient.core.Orient$OShutdownCallListenersHandler.shutdown(Orient.java:1005)
        at com.orientechnologies.orient.core.Orient.shutdown(Orient.java:331)
        at com.orientechnologies.orient.server.OServer.shutdown(OServer.java:493)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary$3.run(ONetworkProtocolBinary.java:2138)
```

**Comment by maggiolo00** [comment]
@rdelangh 
let me check

**Comment by maggiolo00** [comment]
@rdelangh 

i'm not able to reproduce it.  Can you help me on that?

**Comment by rdelangh** [comment]
@maggiolo00 
Typically this happens after the database was opened, and records were inserted to some classes, by which Lucene indexes got updated.
When I do a 'gracefull' shutdown then, the above error appears nearly always in the logfile.

**Comment by maggiolo00** [comment]
@rdelangh 

i did that test without luck.

Are you able to reproduce it in a test db?

**Comment by rdelangh** [comment]
@maggiolo00 can you please define what you consider as a test db ? Our dbase is about 600GB

**Comment by maggiolo00** [comment]
@rdelangh 
i meant   if you can replicate by creating on  a test environment  a fresh new db 
with  a bunch of test classes and lucene test indexes and replicate the exception.

Thanks

**Comment by maggiolo00** [comment]
@rdelangh 

how do you shutdown ODB?

**Comment by rdelangh** [comment]
@maggiolo00 
the shutdown is done with the command
bin/shutdown.sh -h $ourFQDN -P 2424-2430 -u root -p $ourPwd

**Comment by maggiolo00** [comment]
@rdelangh 
just pushed a fix that should should solve the closing issue.
It's available in the 2.2.12-snapshot or it will be in 2.2.12
Thanks.

**Comment by maggiolo00** [comment]
@rdelangh 

are you able to test the fix on your test environment? 

Thanks

**Comment by rdelangh** [comment]
@maggiolo00 
hi Enrico, sorry, still awaiting that I can safely shutdown our current instance, in order to run the v2.2.12 instead.
Could you meanwhile please drop me somewhere a pre-build version of this v2.2.12 snapshot ?

**Comment by maggiolo00** [comment]
@rdelangh 

you can find the snapshots here :
https://oss.sonatype.org/content/repositories/snapshots/com/orientechnologies/orientdb-community/2.2.12-SNAPSHOT/

**Comment by rdelangh** [comment]
@maggiolo00 
Enrico, I installed and started snapshot version 2.2.12-20161019.051435-38

- created a new class "cdr_af_20160626" with a bunch of properties, no records in it yet
- I created a Lucene index on this class:
```
create index idx_cdr_af_20160626_2 ON cdr_af_20160626(FILENAME) LUCENE
```
- the logs of the server receive this : 
```
Error while flushing index via index engine of class OLuceneIndexEngineDelegate.
java.lang.NullPointerException
        at com.orientechnologies.lucene.engine.OLuceneIndexEngineDelegate.flush(OLuceneIndexEngineDelegate.java:69)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.synch(OAbstractPaginatedStorage.java:2366)
        at com.orientechnologies.orient.server.distributed.impl.ODistributedStorage.synch(ODistributedStorage.java:1462)
        at com.orientechnologies.orient.core.index.OIndexManagerShared.createIndex(OIndexManagerShared.java:197)
        at com.orientechnologies.orient.core.index.OIndexManagerProxy.createIndex(OIndexManagerProxy.java:87)
        at com.orientechnologies.orient.core.metadata.schema.OClassImpl.createIndex(OClassImpl.java:1871)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLCreateIndex.execute(OCommandExecutorSQLCreateIndex.java:277)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:74)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:2677)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:2623)
        at com.orientechnologies.orient.server.distributed.impl.ODistributedStorage$2.call(ODistributedStorage.java:314)
        at com.orientechnologies.orient.core.db.OScenarioThreadLocal.executeAsDistributed(OScenarioThreadLocal.java:70)
        at com.orientechnologies.orient.server.distributed.impl.ODistributedStorage.command(ODistributedStorage.java:311)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:69)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1438)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:576)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:321)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:197)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
```

-> issue not resolved with this version, apparently

**Comment by maggiolo00** [comment]
@rdelangh 
do you create the index with Studio or console?

i was not able to reproduce this issue by simple creating an Lucene index from Studio.

**Comment by rdelangh** [comment]
@maggiolo00 
I created the index from console.
Even when no records are added to the class, the logs from the server give the problems about flushing Lucene index...

**Comment by maggiolo00** [comment]
@robfrank 
I'm reopening this. It's not fixed yet. I forgot to unmark this unresolved

**Comment by rdelangh** [comment]
@maggiolo00

I get the same message regularly during the server's activity, not only during its shutdown :

```
Error while flushing index via index engine of class OLuceneIndexEngineDelegate.
java.lang.NullPointerException
        at com.orientechnologies.lucene.engine.OLuceneIndexEngineDelegate.flush(OLuceneIndexEngineDelegate.java:69)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.synch(OAbstractPaginatedStorage.java:2366)
        at com.orientechnologies.orient.core.index.OIndexManagerShared.createIndex(OIndexManagerShared.java:197)
        at com.orientechnologies.orient.core.index.OIndexManagerProxy.createIndex(OIndexManagerProxy.java:87)
        at com.orientechnologies.orient.core.metadata.schema.OClassImpl.createIndex(OClassImpl.java:1871)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLCreateIndex.execute(OCommandExecutorSQLCreateIndex.java:277)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:74)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:2677)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:2623)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:69)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1438)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:576)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:321)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:197)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
```

-> is there any progress in analyzing/resolving this issue ?

**Comment by maggiolo00** [comment]
hi @rdelangh 

this is in the create index. Do you create index from Java API?
Is the server standalone or distributed.

I was not able to reproduce this. 
BTW the problem is in the lifecycle of the index, i'm trying to find the best way to solve it.

**Comment by rdelangh** [comment]
@maggiolo00 
hi Enrico, there is no index creation going on.
The server is standalone:

```
$ ps -aef | grep 'java \-server'
orientdb 38640     1 24 11:15 pts/0    00:15:59 java -server -Xms512m -Xmx6000m -Djna.nosys=true -XX:+HeapDumpOnOutOfMemoryError -XX:MaxDirectMemorySize=512g -Djava.awt.headless=true -Dfile.encoding=UTF8 -Drhino.opt.level=9 -Dstorage.diskCache.bufferSize=32000 -Djava.util.logging.config.file=/opt/orientdb/orientdb-community-2.2.12-SNAPSHOT.20161019/config/orientdb-server-log.properties -Dorientdb.config.file=/opt/orientdb/orientdb-community-2.2.12-SNAPSHOT.20161019/config/orientdb-server-config.xml -Dorientdb.www.path=/opt/orientdb/orientdb-community-2.2.12-SNAPSHOT.20161019/www -Dorientdb.build.number=UNKNOWN@rfbb761d8baf68268fccf5c7e8fc9900f5d4dadaf; 2016-10-19 01:49:10+0000 -cp /opt/orientdb/orientdb-community-2.2.12-SNAPSHOT.20161019/lib/orientdb-server-2.2.12-SNAPSHOT.jar:/opt/orientdb/orientdb-community-2.2.12-SNAPSHOT.20161019/lib/*:/opt/orientdb/orientdb-community-2.2.12-SNAPSHOT.20161019/plugins/* com.orientechnologies.orient.server.OServerMain
```

**Comment by maggiolo00** [comment]
@rdelangh 

this stack derive from an index creation

```
Error while flushing index via index engine of class OLuceneIndexEngineDelegate.
java.lang.NullPointerException
        at com.orientechnologies.lucene.engine.OLuceneIndexEngineDelegate.flush(OLuceneIndexEngineDelegate.java:69)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.synch(OAbstractPaginatedStorage.java:2366)
        at com.orientechnologies.orient.core.index.OIndexManagerShared.createIndex(OIndexManagerShared.java:197)
        at com.orientechnologies.orient.core.index.OIndexManagerProxy.createIndex(OIndexManagerProxy.java:87)
        at com.orientechnologies.orient.core.metadata.schema.OClassImpl.createIndex(OClassImpl.java:1871)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLCreateIndex.execute(OCommandExecutorSQLCreateIndex.java:277)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:74)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:2677)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:2623)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:69)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1438)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:576)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:321)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:197)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
```

**Comment by maggiolo00** [comment]
@rdelangh 

i've added extra checks. You should not receive NPE

**Comment by rdelangh** [comment]
@maggiolo00 
Enrico, sorry to say, but the error shows up again in the server logfile : 

```
$ANSI{green {db=cdrarch}} Error while flushing index via index engine of class OLuceneIndexEngineDelegate.
java.lang.NullPointerException
        at com.orientechnologies.lucene.engine.OLuceneIndexEngineDelegate.flush(OLuceneIndexEngineDelegate.java:69)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.synch(OAbstractPaginatedStorage.java:2413)
        at com.orientechnologies.orient.core.index.OIndexManagerShared.createIndex(OIndexManagerShared.java:197)
        at com.orientechnologies.orient.core.index.OIndexManagerProxy.createIndex(OIndexManagerProxy.java:87)
        at com.orientechnologies.orient.core.metadata.schema.OClassImpl.createIndex(OClassImpl.java:1871)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLCreateIndex.execute(OCommandExecutorSQLCreateIndex.java:277)
        at com.orientechnologies.orient.core.sql.OCommandExecutorSQLDelegate.execute(OCommandExecutorSQLDelegate.java:74)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.executeCommand(OAbstractPaginatedStorage.java:2724)
        at com.orientechnologies.orient.core.storage.impl.local.OAbstractPaginatedStorage.command(OAbstractPaginatedStorage.java:2670)
        at com.orientechnologies.orient.core.command.OCommandRequestTextAbstract.execute(OCommandRequestTextAbstract.java:69)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.command(ONetworkProtocolBinary.java:1438)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.executeRequest(ONetworkProtocolBinary.java:576)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.sessionRequest(ONetworkProtocolBinary.java:321)
        at com.orientechnologies.orient.server.network.protocol.binary.ONetworkProtocolBinary.execute(ONetworkProtocolBinary.java:197)
        at com.orientechnologies.common.thread.OSoftThread.run(OSoftThread.java:77)
```

Running now version 2.2.13-20161027.133116-9

**Comment by maggiolo00** [comment]
@rdelangh 

just pushed the fix. It will be available in the next snapshot

**Comment by rdelangh** [comment]
meanwhile, database cannot be opened anymore after running with 2.2.13* snapshots, see #6884

Waiting for that issue to be resolved first ...

**Comment by rdelangh** [comment]
@maggiolo00 
1) the database is enabled again, issue #6884 is resolved
2) I haven't seen any issue with the Lucene indexes anymore in the 2.2.1-* snapshots anymore, so I hope to be able to assume that this issue has been resolved.

-> this issue can be closed, many thanks !

**Comment by maggiolo00** [comment]
Thanks

@rdelangh
