### ISSUE TITLE
3.0 Connection Pool throws OTokenSecurityException after a night of inactivity

### ISSUE THREAD

**Issue by ShakAttacked** [orientechnologies/orientdb#8050]
### OS: Centos  

After a night of inactivity, I started to run my tests and I received this exception.
com.orientechnologies.orient.enterprise.channel.binary.OTokenSecurityException: The token provided is expired 

It's received after a connection was retrieved from the pool and only throws an error when an sql query is made to the database.  

Thanks,
Safwan

[2018-02-01 10:21:10.342][http-bio-8080-exec-13][ERROR][o.t.s.resources.ServiceResource]Error: com.orientechnologies.orient.enterprise.channel.binary.OTokenSecurityException: The token provided is expired 
[2018-02-01 10:21:10.342][http-bio-8080-exec-13][ERROR][o.t.s.resources.ServiceResource]sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
java.lang.reflect.Constructor.newInstance(Constructor.java:422)
com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.throwSerializedException(OChannelBinaryAsynchClient.java:318)
com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.handleStatus(OChannelBinaryAsynchClient.java:275)
com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:191)
com.orientechnologies.orient.client.binary.OChannelBinaryAsynchClient.beginResponse(OChannelBinaryAsynchClient.java:153)
com.orientechnologies.orient.client.remote.OStorageRemote.beginResponse(OStorageRemote.java:1763)
com.orientechnologies.orient.client.remote.OStorageRemote.lambda$networkOperationRetryTimeout$2(OStorageRemote.java:226)
com.orientechnologies.orient.client.remote.OStorageRemote$$Lambda$4/959843086.execute(Unknown Source)
com.orientechnologies.orient.client.remote.OStorageRemote.baseNetworkOperation(OStorageRemote.java:284)
com.orientechnologies.orient.client.remote.OStorageRemote.networkOperationRetryTimeout(OStorageRemote.java:214)
com.orientechnologies.orient.client.remote.OStorageRemote.networkOperationNoRetry(OStorageRemote.java:239)
com.orientechnologies.orient.client.remote.OStorageRemote.beginTransaction(OStorageRemote.java:1903)
com.orientechnologies.orient.core.db.document.ODatabaseDocumentRemote.checkAndSendTransaction(ODatabaseDocumentRemote.java:321)
com.orientechnologies.orient.core.db.document.ODatabaseDocumentRemote.query(ODatabaseDocumentRemote.java:345)

**Comment by tglman** [comment]
Hi @ShakAttacked,

What is happening is the session is expired because the length of a session is by default 1h, and a night without operations is obviously longer, anyway this kind of error should be handled by the orient network layer and a new session should be re-acquired.

What version of orientdb are you using? I fixed a similar issue on the 3.0.0 SNAPSHOT in January.

Regards

**Comment by ShakAttacked** [comment]
Hi @tglman ,

hard to tell.  When i found this, I could've been working on either on RC1 or the 25th or 30th release.. what we can do is close it and if I hit it again, I'll reopen it.  I've moved most of my code into a Plugin now, so I'm not dealing with connection pool now.  However, one feature might outside a plugin and so I'll be able to test it again.

Thanks,
Safwan

**Comment by 2082041S** [comment]
@tglman @ShakAttacked I can still reproduce this issue in 3.0.2.

**Comment by 2082041S** [comment]
Thank you very much for your reply @tglman ! I shall get the latest version and will let you know if Iencounter any more issues :)

**Comment by 2082041S** [comment]
Hi @tglman,

I am afraid I am still reproducing the "Token is expired" issue even when using Orient 3.0.3, just as it did before upgrading Orient's version.

Am I right in saying this is a known Orient issue? 

Regards,
Petre.

**Comment by 2082041S** [comment]
Upgrading to 3.0.3 fixed the issue. My previous comment was due to only upgrading the client to 3.0.3 and forgetting to upgrade the server as well.
